### ISSUE TITLE
[1.12] I'm in the latest version of forge...

### ISSUE THREAD

**Issue by Migmag789** [Ellpeck/ActuallyAdditions#823] opened 2017-06-29 11:07 UTC
... but AA is crashing :/

**Comment by Ellpeck** [comment] 2017-06-29 11:08
Duplicate of #822 which is a duplicate of #820 which is a duplicate of #811.
Use your eyes, people.

**Comment by Migmag789** [comment] 2017-06-29 11:09
Okay, it's just a mistake by myself ^^'

**Closed by Ellpeck** 2017-06-29 11:08 UTC
