### ISSUE TITLE
Question: How does the fishing net work...

### ISSUE THREAD

**Issue by Kaisoul** [Ellpeck/ActuallyAdditions#550] opened 2017-01-03 17:54 UTC
ok i placed fishing net over water dug out another 3+ blocks under the net and placed a small crate over the net.      Am i doing something wrong here?

**Comment by Ellpeck** [comment] 2017-01-03 17:57
The fishing net needs to be placed over water with a storage container somewhere around it, like stated in the book.
Then you need to wait, it takes a long time to catch a fish.

**Comment by Ellpeck** [comment] 2017-01-03 17:57
Please explain further if you think there is a bug occuring here, otherwise close this issue.

**Comment by Kaisoul** [comment] 2017-01-03 17:59
estimate how many minecraft days does it take to have one catch?

**Comment by Ellpeck** [comment] 2017-01-03 18:01
At least 15000 ticks, so about one Minecraft day.

**Comment by Kaisoul** [comment] 2017-01-03 18:01
so far we have weighted 3 minecraft days for the net to catch a fish.

**Comment by Ellpeck** [comment] 2017-01-03 18:01
I can't reproduce this.
Post a screenshot of your setup.

**Comment by Kaisoul** [comment] 2017-01-03 18:01
-k- one sec

**Comment by Kaisoul** [comment] 2017-01-03 18:04
![2017-01-03_12 02 18](https://cloud.githubusercontent.com/assets/18170370/21617654/a5d8ef80-d1ac-11e6-9d9d-a9b2274081a5.png)

**Comment by Kaisoul** [comment] 2017-01-03 18:04
under the net is over 3+ blocks of water.   Directly above the net is the crate.

**Comment by Kaisoul** [comment] 2017-01-03 18:05
it just caught a fish.... after posting this.

**Closed** 2017-01-03 18:05 UTC
