### ISSUE TITLE
Fluid Laser Relays not interacting with Thermal Expansion machines outputting liquid

### ISSUE THREAD

**Issue by Numpty101** [Ellpeck/ActuallyAdditions#718] opened 2017-03-29 00:04 UTC
The Machine is set to output on top:
![fluidrelay1](https://cloud.githubusercontent.com/assets/26753158/24432524/5de39904-146a-11e7-86b7-bead4075ae8b.png)

The Lasers are connected:
![fluidrelay2](https://cloud.githubusercontent.com/assets/26753158/24432528/67e78eb0-146a-11e7-8e73-03564dc70f82.png)

Changing the flow of the relays with a compass has no effect.

Furthermore they seem to be able to push fluid into Thermal Expansion machines (namely dynamo's and tanks), just not pull out directly (can use an Ender IO tank as an inbetween).

**Comment by Ellpeck** [comment] 2017-03-31 04:59
Is this reproducable with any other machine from Thermal Expansion?

**Comment by Ellpeck** [comment] 2017-05-20 18:04
Closing because of missing response

**Closed by Ellpeck** 2017-05-20 18:04 UTC
Labels: bug, investigate
