### ISSUE TITLE
Store phantom blocks bound target as an offset

### ISSUE THREAD

**Issue by remuladgryta** [Ellpeck/ActuallyAdditions#1298] opened 2019-11-20 00:29 UTC
If the various phantom blocks stored their linked target as an offset from their own coordinates instead of absolute coordinates it would improve compatibility with mods that can move tile entities.

This would make e.g. Project Red frame machines work with phantom blocks: if you move a frame machine with a phantom energyface bound to some other machine that's also attached to the same frame machine, you would expect the connection to remain.

**Comment by TomyLobo** [comment] 2019-11-23 13:27
We have the same issue with Funky Locomotion.
Phantom Placer goes completely bonkers, saying the target is obstructed.
I'm tempted to attempt to make these offsets myself, but I don't want to put a lot of work into it if it ends up being rejected because that is not a change they want to see.

**Comment by Ellpeck** [comment] 2020-03-29 16:41
Duplicate of #1040, actually

**Closed by Ellpeck** 2020-03-29 16:41 UTC
Labels: improvement
