### ISSUE TITLE
[Issue] Compat other mods (EverlastingAbilities) 

### ISSUE THREAD

**Issue by accessdenied0** [Ellpeck/ActuallyAdditions#223] opened 2016-09-01 05:30 UTC
Hello dear @Ellpeck,

I recently run into some issues with the newest update of your mod. Some of the machines (Atomic Reconstructor) didn't work. After an other issue with this EverlastingAbilities: 
Issue: https://github.com/CyclopsMC/EverlastingAbilities/issues/13

and removing EverlastingAbilities, it worked again. Strangely enough it didn't put out any message in my console to report.

The main reason why I wrote my issue like that is, that the issue with EverlastingAbilities is more severe but I felt like I have to mention my other problem in some case, too.

If you want to write two seperate issues, that is fine for me, too. I'll rewrite this.

access_denied

**Comment by Ellpeck** [comment] 2016-09-01 05:41
So has this only been happening with the newest update (r61) of Actually Additions?
The crash report doesn't appear to have anything to do with Actually Additions, so I don't know what is going on here.

**Comment by Ellpeck** [comment] 2016-09-01 05:56
So, am I getting it right that all of the problems only appear with Everlasting Abilities installed?

**Comment by accessdenied0** [comment] 2016-09-01 06:07
Hey @Ellpeck,

The problem with not working machines (only tested Coal-Generator and Atomic Reconstructor) is only in the newest version of Actually Additions (r61) and with or without Everlasting Abilities. 
I have the feeling it might be Tesla-1.10.2-1.2.1.49.jar , but I'm not sure about. I tried it multiply times with breaking and placing and experienced for example that the energy was emptying out the Coal-Generator but didn't reached the Reconstructor. I placed it against Glass and Stone and only after breaking the Reconstructor I got an update of his energy, but he still didn't worked.

The strange thing after (might be the restart) it is working again. Maybe an unique issue but maybe you can take a look into this. 

I'll try to post my modlist very soon...

access_denied

**Comment by accessdenied0** [comment] 2016-09-01 06:17
Addition: 

This problem seem to not connected with EverlastingAbilites, because I run into new issues: 

After I crafted and placed a Block Breaker I was able to break one block, after this I broke him and placed him a bit further. He broke the block behind him on the floor and quit aftet that the work: 
http://puu.sh/qVWBX/c441a74887.png

in addition his GUI isn't accesable anymore and this throws minecraft in the console:
http://pastebin.com/v6sVYUaj

I'll try to downgrade Actually Addition to r60 and look if this appears, too. Maybe it is still a mod compat problem?

access_denied

**Comment by Ellpeck** [comment] 2016-09-01 06:20
The only thing I changed about the Block Breaker is the way it updates.
Yo @blay09, do you think these issues could be caused by that runnable tasks thing you told me about? :o

**Comment by accessdenied0** [comment] 2016-09-01 06:29
@Ellpeck 
I downgraded it to r60. It seem to work now just fine. I broke and placed all blocks I noticed the issues with (Atomic Reconstructor, Coal-Generator, Block Breaker) and used them. It seem to work now just fine. 
I hope this update isn't too soon, but I feel like it is indeed something with r61.

**Comment by Ellpeck** [comment] 2016-09-01 06:30
I'll try to revert a change and then send you a test version later today.

**Comment by blay09** [comment] 2016-09-01 09:01
It's probably receiving tile entitiy updates for positions that don't have a tile entity on them. It shouldn't have anything to do with making networking thread-safe unless you manually send SPacketUpdateTileEntity from within your packet handlers.

**Comment by Ellpeck** [comment] 2016-09-01 11:45
No, I am only sending the custom one and overriding the vanilla update methods.
But I haven't changed anything other than that since the last update is the weird thing :x

**Comment by Ellpeck** [comment] 2016-09-01 11:50
Actually.. this might be the cause.
Gah.
https://github.com/Ellpeck/ActuallyAdditions/commit/3c727542ac702073d2819e81144a2078f5a8cd20 
That is a total mess anyways, but so is Vanilla. :v

**Comment by Ellpeck** [comment] 2016-09-01 15:12
http://puu.sh/qWiNo/daa267e16c.jar
Could you try with this version please, @accessdenied0?
Also, if it doesn't work, send the entire log please.

**Comment by accessdenied0** [comment] 2016-09-01 18:07
@Ellpeck 

The machines work until I break or place them. Still the same issue... here is my console Log: 
http://puu.sh/qWsLa/472a0b50d6.txt

It is weird that r60 seem to work just fine.

**Comment by Ellpeck** [comment] 2016-09-01 18:18
Try removing all of the other mods and see if that fixes it.
If so, try removing them in batches to see which mod it actually is.

**Comment by blay09** [comment] 2016-09-01 18:35
I managed to reproduce the issue with just Actually Additions in a dev env, so removing mods won't help. (To reproduce: Place Auto Breaker, have it break one block, break it in Survival mode, place at different spot, opening its GUI will now insta-close it and post the exception in log)

**Comment by Ellpeck** [comment] 2016-09-01 18:36
Wh.. I just tested that outside a dev env with just Actually Additions installed, and it didn't do that.
But I was in Creative too, so I guess it's a survival-only thing? O_o

**Comment by Ellpeck** [comment] 2016-09-01 18:41
Oh God, this is embarassing.
I found the issue.

**Closed** 2016-09-01 18:42 UTC
Labels: bug, investigate

**Comment by accessdenied0** [comment] 2016-09-01 18:55
Thank you all for your help and support!

**Comment by Ellpeck** [comment] 2016-09-01 18:56
No probs. You were a great help too :)
