### ISSUE TITLE
server crash due to AA (Description: Ticking block entity)

### ISSUE THREAD

**Issue by trilexcom** [Ellpeck/ActuallyAdditions#910] opened 2017-08-27 16:24 UTC
hi Ellpeck

our Server crashed due to AA in the crashlog said Ticking block entity
 
please let me know if this is AA issue or another mod is causing it or user wrong doing ?

Forge Version : 2461
MC : 1.12.1
AA Version : ActualAdditions-1.12-r118
Modpack : Trilex Pack

Crashlog link 1 : 
https://pastebin.com/gM1LhE4T

Crashlog link 2:
https://pastebin.com/vUHHRj3e

Thanks 

Mat (TrilexCom)

**Comment by Shadows-of-Fire** [comment] 2017-08-27 16:25
Duplicate of #904 (see that issue for a working build)

**Closed by Shadows-of-Fire** 2017-08-27 16:25 UTC

**Comment by trilexcom** [comment] 2017-08-27 16:28
ah thanks
