### ISSUE TITLE
Crash report after updating to forge 14.23.3.2657

### ISSUE THREAD

**Issue by DuelMonster** [Ellpeck/ActuallyAdditions#1071] opened 2018-04-12 19:56 UTC
I'm getting a `NullPointerException: Initializing game` after having updated to forge 14.23.3.2657.
<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-1.12-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/12/18 8:35 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.getCapability(ItemEnergy.java:230)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.hasCapability(ItemEnergy.java:222)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:94)
	at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1162)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_150895_a(ItemEnergy.java:77)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.getCapability(ItemEnergy.java:230)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.hasCapability(ItemEnergy.java:222)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:94)
	at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1162)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_150895_a(ItemEnergy.java:77)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1416518888 bytes (1350 MB) / 2465202176 bytes (2351 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2657 Optifine OptiFine_1.12.2_HD_U_C8 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                        | 8.0.99.99                | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.3.2657             | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | foamfixcore                | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCH   | actuallyadditions          | 1.12.2-r133              | ActuallyAdditions-1.12.2-r133.jar               | None                                     |
	| UCH   | betterbuilderswands        | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | jei                        | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | blockdrops                 | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                     | None                                     |
	| UCH   | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chesttransporter           | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCH   | codechickenlib             | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chickenchunks              | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | clienttweaks               | 3.1.6                    | ClientTweaks_1.12.2-3.1.6.jar                   | None                                     |
	| UCH   | endercompass               | 1.2.6.1                  | EnderCompass-1.12-1.2.6.1.jar                   | None                                     |
	| UCH   | endercore                  | 1.12.2-0.5.18            | EnderCore-1.12.2-0.5.18.jar                     | None                                     |
	| UCH   | enderio                    | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiointegrationtic      | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiobase                | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderioconduits            | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiointegrationforestry | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiointegrationticlate  | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiomachines            | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiopowertools          | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | extrautils2                | 1.0                      | extrautils2-1.12-1.7.5.jar                      | None                                     |
	| UCH   | flatbedrockx               | 1.4.0                    | FlatBedrock-1.4.0_1.12.jar                      | None                                     |
	| UCH   | foamfix                    | 0.8.0-1.12               | foamfix-0.8.0-1.12-anarchy.jar                  | None                                     |
	| UCH   | ftblib                     | 5.0.1.15                 | FTBLib-5.0.1.15.jar                             | None                                     |
	| UCH   | ftbutilities               | 5.0.1.12                 | FTBUtilities-5.0.1.12.jar                       | None                                     |
	| UCH   | lunatriuscore              | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCH   | ingameinfoxml              | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar     | None                                     |
	| UCH   | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | journeymap                 | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | jeresources                | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCH   | kleeslabs                  | 5.4.8                    | KleeSlabs_1.12.2-5.4.8.jar                      | None                                     |
	| UCH   | malisiscore                | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCH   | malisisblocks              | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
	| UCH   | malisisdoors               | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCH   | moreoverlays               | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                  | None                                     |
	| UCH   | netherportalfix            | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
	| UCH   | quickleafdecay             | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCH   | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCH   | refinedstorage             | 1.5.32                   | refinedstorage-1.5.32.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | refinedstorageaddons       | 0.2                      | refinedstorageaddons-0.2.jar                    | None                                     |
	| UCH   | theoneprobe                | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCH   | minersadvantage            | 1.3.14.188               | MinersAdvantage-1.12.2-1.3.14.189.jar           | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: forge-14.23.3.2657
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 3D.zip, Faithful 1.12.2-rv4.zip, ModdedFaithful 1.12.2-rv1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 16
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.01
	OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```
</details>

**Comment by Shadows-of-Fire** [comment] 2018-04-12 20:25
Duplicate of #1068

**Closed by Shadows-of-Fire** 2018-04-12 20:25 UTC
