### ISSUE TITLE
Duping bug with the travelers sack/void sack. The bags do not work due to this with auto insert on.

### ISSUE THREAD

**Issue by CLG-Ytterbium** [Ellpeck/ActuallyAdditions#679] opened 2017-03-12 07:07 UTC
Basically you drop anything on the ground and use the auto insert option and instead of putting the items into the sacks it dupes them. So you pick up the items like normal but you have duped amount in the sack. Without the auto insert it works fine so far. The void sack will not work with the auto insert either because it will just destroy the duped items instead of the items being picked up. I am using the version that is on beyond so the 1.10.2 -r 98 version.

**Comment by Ellpeck** [comment] 2017-03-12 07:42
Duplicate of #674

**Closed by Ellpeck** 2017-03-12 07:42 UTC
