### ISSUE TITLE
[1.12.2]Crash "Ticking World"

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Ellpeck/ActuallyAdditions#1124] opened 2018-06-23 14:15 UTC
the wild plants (except the black lotus) behaive extremely strange.
1. they don't drop anything when mined.
2. you can mine the block below them (which deletes the block you mined without dropping an item) and the plant will just float
3. they randomly seem to crash the game when trying to fiquire out what to drop.

All version numbers are within the log.
[Pastebin](https://pastebin.com/2ctj4qAT)

**Comment by Shadows-of-Fire** [comment] 2018-06-23 16:38
Duplicate of #1123

**Closed by Shadows-of-Fire** 2018-06-23 16:38 UTC
Labels: bug
