### ISSUE TITLE
1.11.2-r106: Item laser disconnected after re-entering world

### ISSUE THREAD

**Issue by Knito58** [Ellpeck/ActuallyAdditions#751] opened 2017-04-29 06:06 UTC
After restarting minecraft and re-entering the world, there may always be missing some random connections between item lasers.

I watch this bug since two months and thought, this was a feature to keep me running and make the game more interesting. But recently I found the (now closed - why?) bug in the issue list.

Imho this has nothing to do with using other mods. It has something to do with the world loading thiingo. I do not use any other dimensions atm (except nether) and enter the world only on the vanilla way.

As it is always a laser line that really hurts, the missing link can become tracked down easily in most cases. Otherwise I spend an hour running around and searching the issue: Why are there no cactee in RS? Of course, the importing link (heavily frequented) from the farm tower (primordial crops, 36 farms atm, still building more farms) was missing and thus blocking the flow in the farm tower system.

Fluid and energy relays look stable atm. 

Anyway: Super good mod! Won't play without it, even with disconnecting lasers :)

System:
MC 1.11.2
Forge 13.20.0.2285
Actually Additions 1.11.2-r106

**Comment by Ellpeck** [comment] 2017-04-29 09:28
I have never been able to reproduce this issue, that's why all the other reports about it were eventually closed. Please try reproducing it in a creative world and try narrowing down the exact cause if you manage to make it happen.

**Comment by Knito58** [comment] 2017-04-29 19:04
Ok. I never did anything special before re-entering. Mostly I left the game when stopping to play mc. Then, after re-entering, the bug stays undiscovered some time until I see something's going wrong. Then obviously at world-loading time there was cut at least one item laser connections. Sometimes more than one. I'll make a nice creative world with *many* item laser connections. The more connections, the more likely they seem to fail. I'll be back.
:)

**Comment by Ellpeck** [comment] 2017-04-29 19:12
Please also try to find out if this really is limited to only Item Lasers, or if it also happens with other ones.

**Comment by Knito58** [comment] 2017-04-29 21:48
ok. I'll make a lot of connections.

**Comment by Knito58** [comment] 2017-05-01 10:25
Hi @Ellpeck,

I can state that the issue is not only limited to item lasers. In my SMP world which I play atm there is also sometimes some fluid laser link missing.

As you asked for a creative test world I came up with a farming tower which should produce coal, canola oil, iron and gold. I entered and left this world from different places. But there never was any disconnecting laser until now.

But I'm very happy to report some other issues in this testing:

- Some of the essences go to the prio 0 overflow instead of finding the prio 20 crafter
- There's ore stuck in the system which does not find the furnaces

Ok. I admit that its a *long*, *loooooooooooooonnnnnnng* way for the items sent through this maze, but this is no excuse for them to go to the wrong place.

[https://www.dropbox.com/s/843creasufzty9w/LaserRelayConnectionTest.zip?dl=0](Test World) (4.014kb)

Mods needed for this world to run:

MC 1.11.2, Forge 13.20.0.2285 (maybe not necessary but the save was done with that)
Actually Additions (for everything that matters)
RFTools (for the crafters)
Primordial crops (for the coal, iron and gold crops)

I have some more mods running, my welcome screen states 75 - which is not true. Just ignore the world loading warnings if you have installed the three mods mentioned above.

Greetings,
Konitor

**Comment by Ellpeck** [comment] 2017-05-01 11:08
I will check this out later, thanks a lot.

**Comment by Ellpeck** [comment] 2017-05-01 15:08
So, are you saying that there is disconnecting going on even in this test world?
If so, did you manage to pin down the cause of it?

**Comment by Knito58** [comment] 2017-05-01 18:14
No Sir. In this test world there never was any disconnected laser for me. In spite of heavy wiring and using up more connections than in the last three worlds together. I left the world many times and re-entered it. Nothing happened. I left it from different places to see if the distance to the lasers would make a difference. Nothing. 

I had the missing links only in no-cheat SMP worlds. And lastly there was also a fluid link missing.
But: What about the stuck ore and the essences which walk to the lo prio lava pit instead of the hi prio crafter? Not all go that way. Some eventually find the crafter.
Should I open a new issue or is this already known?

**Comment by Ellpeck** [comment] 2017-05-01 19:36
I didn't look at the world. Did you configure any ESDs you possibly used right and did you re-configure them to the right slot amount once you connected new Laser Relays?

**Comment by HellEye** [comment] 2017-05-03 12:07
I'll add that for some reason ALL my energy relays disconnect about 50% of the time I enter the world. Pretty annoying. Don't really know the cause either, just saying that it's not just Knito's setup. I'm playing All the Mods for 1.11.2 currently, maybe it's a conflict somewhere. There's too many mods to check for that though. Good luck in fixing it if you can!

**Comment by Ellpeck** [comment] 2017-05-03 12:34
I have, still, not once been able to reproduce it.
Occasionally there's some people reporting it, but I have no idea why.
I made a fix a couple of days ago that might work, though.

**Comment by Ellpeck** [comment] 2017-05-03 12:34
Closing this for now.

**Closed by Ellpeck** 2017-05-03 12:34 UTC
Labels: bug, investigate

**Comment by Knito58** [comment] 2017-05-03 19:54
OK I'll check out the r107 version. Thank you.

No I didn't use any ESDs, only item interfaces and lasers. Using normal item lasers as backbone and the advanced ones for distributing the items.

The wiring usually works - but the test world has so many surplus lasers to force problems. In princip, it is a short and working wiring that is prolongated artificially.

I'm so sorry you didn't see it....
