### ISSUE TITLE
IMPORTANT MAJOR AND GENERAL BUG (1.9 and 1.9.4) : Catched unhandled exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#98] opened 2016-05-29 21:21 UTC
IMPORTANT : THIS BUG IS GENERAL TO ALL THE MODS OF MINECRAFT 1.9 and 1.9.4
-------------------------------------------------------------------------------------------------------------------------------

A strange bug happens when a tile entity is destroyed, Almost all the time an exception is thrown when the bug happens : Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException 
For some particular blocks, Minecraft totally freezes and finished to crash with the error code -805306369 without any crash report. Here is the list of all the blocks wich are confirmed to provocate Minecraft to freeze and crashs with this error.

- Building Brick : all the glass, ice and packed ice blocks
- Deep Resonance : resonant crystal
- Biomes O Plenty : celestial crystal
- Botania : mana prism
- Blood Arsenal : blood stained glass block and pane
- Evilcraft : darktank
- EnderIO : killer joe, zombie generator, all the fused quartz glasses
- Random Things : lapis lamp, quartz lamp, rainbow lamp, biome glass, spectre block, fluid display

All these blocks follow the same error, only the name of the tile entity between the [ ] changes. Here is an example of how the error happens. The example is made with the resonant crystal of deep resonance. This is a full log and contains the launching of minecraft and the loading of a world, the moment where I brick the block and the bug happens is the moment where the exception [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException is thrown : http://pastebin.com/KhwV1WKg

-------------------------------------------------------------------------------------------------------------------------------

Moreover some tile entities wich has brokner provocates Minecraft to totally crash with a crash report. Here is the list of all the block concerned and their crash report

- EvilCraft : box of eternal closure http://pastebin.com/JzRYf5Ex
- Cooking for block heads : fridge and oven http://pastebin.com/vcmx49qn http://pastebin.com/6zd4qq5w
- Storage Drawers : framing table http://pastebin.com/3077W3Wz

-------------------------------------------------------------------------------------------------------------------------------

I let you know that all the tests possible has already been made before I create this general issue and post it. I already tried to :
- Test the mod one by one only by installing them and forge without any other mods
- Change of Forge Version
- Change between the 1.9 and 1.9.4 version
- Change of mod version
- Play without optifine and any shaders
- Switch between the creative and survival mode
Nothing of all that change anything, the bug still happens in the same way for the same blocks listed at the top. 

-------------------------------------------------------------------------------------------------------------------------------

I precise that almost all the mods in Minecraft 1.9.4 and 1.9 are touched by this bug, because even if they don't provocate Minecraft to freeze or crash, almost always at each time a tile entity is broken, the exception Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException is thrown.
I precise too that the list of all the tile entities listed at the top can be incomplete. I want you know that I tried to break block by block all the blocks of almost all the most popular mods on 1.9.4 and 1.9, so for summarizing something like 50 mods with more than 2000 blocks. So it's possible that I missed some blocks.
It's why I send this issue to all the mods even if no ones of their block are concerned by the bug.
I invite all the mod developpers to try by themselves to break all the tile entities of their mod for seeing they provocate the throwing of the exception, and maybe causes Minecraft to freeze.

**Comment by Ellpeck** [comment] 2016-05-29 21:35
Try reproducing this with just Actually Additions installed.

**Comment by Ellpeck** [comment] 2016-05-29 21:58
Can't reproduce with just Actually Additions.
Neither in dev environment, nor outside.
Closing for now.

**Closed by Ellpeck** 2016-05-29 21:58 UTC
Labels: wat

**Comment by Hypsellis** [comment] 2016-05-29 22:01
Ok I just retried it. In the case of Actually Additions, no blocks are touched by thig bug. I'm sorry to have bothered you with that. A lot of blocks and mods are touched by this bug, and I haven't been able to try all the blocks ones by ones. So I prefer to share the existence of this error to all the developpers wich belong big mods. I hope you understand it.
I curruntly deal with a group of haters because I sended this issue to more than 10 mods, so for them it's spam. Thank you to haven't judged me on that, and sorry to have bothered you with this error.

**Comment by Kilobyte22** [comment] 2016-05-29 22:23
Please verify bugs before reporting them. This involves installing only that one mod and trying to reproduce it. Mass spamming the same issue to hundreds of mods does not help in any way.

**Comment by Kilobyte22** [comment] 2016-05-29 22:35
Apparently your issue is caused by running out of memory. Please increase the memory allocated to minecraft in your launcher. Source is in your log file:
```
Minecraft has crashed with the stop code -805306369.
```
See also http://hopper.minecraft.net/help/exit-code/code-805306369/

**Comment by Hypsellis** [comment] 2016-05-29 22:36
Yeah sorry for having published this issue on your github. Some of your block threw the exception Catched unhandled exception [name of the tile entity] java.lang.NullPointerException even if they didn't freeze the game. So I wasn't sure if this mod was linked with the error too. But from what the others who are concerned by the freezing error told me, the exception is cause by Waila and isn't linked to the freezing and crashing error, so yeah sorry for the bothering.

**Comment by Hypsellis** [comment] 2016-05-29 22:37
It's impossible for the memory thing. I have 16 Go of RAM, and I setted my instence for it uses until 12 Go. In maximum Minecraft uses 8 Go, and it doesn't prevent the bug to happen.

**Comment by XDjackieXD** [comment] 2016-05-29 22:38
Your crash logs from Botania and EnderIO suggest that your Minecraft instance is only running on 1GB of RAM.

**Comment by Kilobyte22** [comment] 2016-05-29 22:39
Your launch parameters include `-Xms512m -Xmx12032m`. I am no jvm expert, but i am fairly sure you should increase the Xms option too.

**Comment by Hypsellis** [comment] 2016-05-29 22:43
If it was the case, Minecraft could even not launch it with all the mods I use, but if you don't trust me, look by yourself.
![capture](https://cloud.githubusercontent.com/assets/17103411/15636449/7d96417a-25ff-11e6-96f8-566e690a4c50.PNG)

**Comment by XDjackieXD** [comment] 2016-05-29 22:50
Could you please try any other Forge version? You are currently using the latest snapshot and maybe it is causing your troubles (even if I can neither reproduce your issue nor have seen a Minecraft modpack needing more than 4GB of RAM).
I've even gone as far as starting my windows VM (which has 8GB of RAM and an AMD GPU) and trying myself with the same Java, Forge & Mod version and couldn't reproduce it...

**Comment by Hypsellis** [comment] 2016-05-29 22:52
I tried with many version of Forge, and it doesn't change anything. I ask me if this bug isn't caused by the 1.9 itslef because it touches too ender portal frame with an eye inside.

**Comment by XDjackieXD** [comment] 2016-05-29 23:28
Well the first thing you should check: Does it also happen with vanilla MC? If yes it is a vanilla issue. If no does it happen with Forge only? If yes report to the Forge team.
Anyways: It has no sense to discuss this here any further as it is clearly not related to ActAdd. Please report any further issues to the respective persons as described above.
