### ISSUE TITLE
r132 breaks Crafting Tweaks compatibility for portable crafter

### ISSUE THREAD

**Issue by Xetaxheb** [Ellpeck/ActuallyAdditions#1055] opened 2018-03-21 03:13 UTC
Versions: CraftingTweaks_1.12.1-8.1.6.jar, ( ActuallyAdditions-1.12.2-r132.jar or ActuallyAdditions-1.12.2-r133.jar )

r133 doesn't work either. r131 works fine.

Reproduction: craft "crafting table on a stick", open it up, put in wood above wood for stick recipe, right click

Expected behavior: get up to 1 stack of sticks (64 by default) on cursor, depending on wood used

Actual behavior: get 4 sticks on cursor, can't continue right clicking for more

**Comment by Shadows-of-Fire** [comment] 2018-03-21 03:50
is FastWorkbench present?

**Comment by Xetaxheb** [comment] 2018-03-23 02:42
Yes

**Comment by Xetaxheb** [comment] 2018-03-23 03:09
Tested ActuallyAdditions-1.12.2-r133-783.jar (compiled 15 mins ago), still not working.

**Comment by Shadows-of-Fire** [comment] 2018-03-23 03:14
Works just fine after that commit with Crafting Tweaks 8.1.8 and Forge 14.23.2.2632, with and without FastWorkbench.

**Comment by Xetaxheb** [comment] 2018-03-23 03:41
Not working for me with FastWorkbench loaded.
The pack I'm using is modern skyblock 3 (3.1.5.3) https://pastebin.com/vPQ3jPWa

CT8.1.8 and AAr133.783 work together, but only if I remove fastworkbench's jar.

**Comment by Shadows-of-Fire** [comment] 2018-03-23 03:44
Still works as intended with FastWorkbench 1.2.1 present

**Comment by Xetaxheb** [comment] 2018-03-23 04:04
Hmm.. updated to FastWorkbench-1.12.2-1.2.1.jar (with CraftingTweaks_1.12.2-8.1.8.jar and ActuallyAdditions-1.12.2-r133-783.jar) and it's still not working out.

Later when I have time, i'll disassemble the pack a few jars at a time and see if I can find another conflict; but it definitely works when fastworkbench is straight up removed.

**Comment by Shadows-of-Fire** [comment] 2018-03-23 04:12
I suppose I am testing in a more isolated environment, but the addition/removal of mods shouldn't change how this compat is being received.  Odd.

**Comment by Shadows-of-Fire** [comment] 2018-03-23 04:17
Actually, I can think of something that might be doing it.  If another mod causes AA to load after crafting tweaks for whatever reason, the IMC message may be sent too late.  Let me try another commit.

**Comment by Xetaxheb** [comment] 2018-03-23 12:44
Uh.. so instead of doing a full teardown, I quickly narrowed it down to this to reproduce:

Literally just run a mc 1.12.2 with forge installed and delete everything but /mods/ containing only AA133.786, CT8.1.8, FW1.2.1

It doesn't work

I'm not sure how you're having success in your test environment. Normal crafting table doesn't even work with 786, but inventory 2x2 does.

If I remove FW, portable and table work.
(tested 783 too, same results)

Probably not relevant, but my forge is 2624

**Comment by Shadows-of-Fire** [comment] 2018-03-23 15:29
Hm.  What operating system are you on?

**Comment by Xetaxheb** [comment] 2018-03-23 23:58
win7 pro 64bit java 1.8.0_161

but there haven't been input differences in the libraries in years so I think it's barking up the wrong tree

**Comment by Shadows-of-Fire** [comment] 2018-03-24 00:00
Yeah I don't think that has anything to do with it, now that I look more closely at it.  I'm really confused as to whats going on.  I should probably have a third person test and report back.

**Comment by Xetaxheb** [comment] 2018-03-24 00:19
My test setup currently: Fresh curse mod profile, ct 8.1.8 aa133.787 fw1.2.1 
prep: new superflat, spawn logs, craft bench and test, craft ctoas and test
test: logs>planks or planks>stick recipe, right click output
expectation: get stack out
result: get one unit (4 plank or stick) and unable to right click for more

notes: not a visual glitch and same test with FW removed works properly as expected

**Comment by Xetaxheb** [comment] 2018-03-24 00:34
tests

AA131, CT816, FW112: works
AA131, CT816, FW121: works
AA131, CT818, FW121: works? ??? strange cause I just tested that and it hadn't, maybe user error on that one test
AA133, CT816, FW121: doesn't work
AA133, CT818, FW121: doesn't work

**Comment by Shadows-of-Fire** [comment] 2018-03-24 00:43
Well this is the end of this mystery... https://github.com/blay09/CraftingTweaks/blob/1.12/src/main/java/net/blay09/mods/craftingtweaks/client/ClientProxy.java#L243
Apparently that slot *needs* to be a SlotCrafting, which FastWorkbench doesn't use.  Time to go wrap everything in misery like I had to do in 1.1.0
(This is a FastWorkbench issue, so I'm gonna close this)

**Closed by Shadows-of-Fire** 2018-03-24 00:43 UTC
