### ISSUE TITLE
Crash: at de.ellpeck.actuallyadditions.mod.blocks.BlockGreenhouseGlass.updateTick

### ISSUE THREAD

**Issue by VladimirMangos** [Ellpeck/ActuallyAdditions#1181] opened 2018-09-26 18:00 UTC
https://paste.dimdev.org/elotujufiq.mccrash

In game for me it happens at move Black Quartz from inventory to chest (can't reproduce).

Repeat one more time in another game moment. So not related to my game activity as I think.

**Comment by sandalle** [comment] 2018-09-26 18:13
Same, happens once I log into my existing world after upgrading from ActuallyAdditions-1.12.2-r140 to ActuallyAdditions-1.12.2-r141.

Dedicated server crash: https://pastebin.com/69j8ceeZ
Minecraft 1.12.2
Forge Mod Loader: 1.12.2-14.23.4.2760

**Comment by Shadows-of-Fire** [comment] 2018-09-26 19:07
Duplicate of #1180

**Closed by Shadows-of-Fire** 2018-09-26 19:07 UTC
