### ISSUE TITLE
Vampirism bat mode makes storage crate upgrades destroy crate contents without upgrading 

### ISSUE THREAD

**Issue by Tarod7** [Ellpeck/ActuallyAdditions#748] opened 2017-04-26 15:25 UTC
version 1.10.2 minecraft with forge 12.18.3.2281

on Actually Additions r105 with Vampirism 1.1.0 beta.2

Going to post this over on the Vampirism mod issue page as well.

to get into bat mode you use the 
/vampirism level Vampire 10 "playername" 
command

Let me know if you anything clairified.

**Comment by Tarod7** [comment] 2017-04-26 15:28
https://github.com/TeamLapen/Vampirism/issues/162

**Comment by Ellpeck** [comment] 2017-04-26 15:37
This doesn't make any sense at all, as I just use the normal right clicking behavior code.
Something weird must be going on with Vampirism.

**Comment by Tarod7** [comment] 2017-04-26 15:58
Bat mode is supposed to disable most actions. I'm not sure if that has anything todo with it.

**Comment by Tarod7** [comment] 2017-04-26 20:09
Looks like he may have made it so instead of disabling block placement it lets you place and immediately breaks the block and returns it to you.

**Comment by Tarod7** [comment] 2017-04-26 21:58
This is what he said in the other thread.

> Thx for reporting. I might have found the problem already, but I don't have time to think about a solution right now.
Just writing down, what I found out:
When upgrading a chest, ActualllyAdditions copies the inventory from the old tile entity, then changes the block and writes the items to the new inventory in Item#onUse and returns EnumActionResult.SUCCESS
https://github.com/Ellpeck/ActuallyAdditions/blob/b8667c1e1e4faffd23c24774746ecf071f1dc6bf/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemChestToCrateUpgrade.java#L43

After the blocks have been changed, Forge posts a BlockEvent.PlaceEvent which is canceled by Vampirism.
ForgeHooks#onPlaceItemIntoWorld around line 800.

Because the event is canceled, Forge rolls back any block changes. During that rollback the chest/tile entity content is somehow lost. It seems that Forge tries to reconver the TE data, but it does not seem to work.

Will take a closer look at this soon

**Comment by Ellpeck** [comment] 2017-04-27 04:15
Seems to be an issue on Vampirism's side then. Closing for now.

**Closed by Ellpeck** 2017-04-27 04:15 UTC
Labels: waiting, wat

**Comment by maxanier** [comment] 2017-04-28 12:07
Is there a specific reason you are clearing out the old chest's/TileEntity's inventory?
https://github.com/Ellpeck/ActuallyAdditions/blob/dd6d250e2f3fd90f27348ebd06fef113c16423cd/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemChestToCrateUpgrade.java#L53

The problem is: The BlockPlace event is thrown after the item placed the block. If the event is canceled by any mod (e.g. Vampirism) Minecraft restores the Block and the TileEntity. But since you cleared the inventory of the old tile before it was stored (during setBockState of the new chest), it's inventory is empty and all items are lost.
