### ISSUE TITLE
Drill and Fortune Augment Don't Work Properly

### ISSUE THREAD

**Issue by fmease** [Ellpeck/ActuallyAdditions#281] opened 2016-10-15 15:15 UTC
Pack: FTB HermitPack

Drills - even with fortune augment I-II - only mine 1 item from an ore. E.g. redstone and coal ores only drip one redstone dust/ coal item

**Comment by Ellpeck** [comment] 2016-10-15 18:13
I can't reproduce this.
Try removing mods and see if that fixes the issue.

The best way to do it is to remove half of the mods, test it, then remove half of the ones left and so on. Gets it done a lot faster :)

**Comment by Ellpeck** [comment] 2016-10-20 17:42
Any update on this?

**Comment by Ellpeck** [comment] 2016-10-26 18:18
Closing this due to missing response. Reopen the issue if your problem persists.

**Closed by Ellpeck** 2016-10-26 18:18 UTC
Labels: bug, investigate, waiting
