### ISSUE TITLE
[1.12] Adding ardite to crusher results in ticking entity crash

### ISSUE THREAD

**Issue by Seth0067** [Ellpeck/ActuallyAdditions#906] opened 2017-08-23 18:01 UTC
1) place ardite ore block into crusher
2) game will crash and world will not load giving below crash report.

[paste](https://pastebin.com/F0Zyv56q)

**Comment by Shadows-of-Fire** [comment] 2017-08-23 18:02
Duplicate of #904

**Closed by Shadows-of-Fire** 2017-08-23 18:02 UTC
