### ISSUE TITLE
Some buttons not working on a Sponge server 

### ISSUE THREAD

**Issue by Eufranio** [Ellpeck/ActuallyAdditions#587] opened 2017-01-21 12:40 UTC
I found that some buttons aren't working on my sponge server. Some appears red, some doesn't work. Here are examples:

Void Sack:
![1](https://cdn.discordapp.com/attachments/200785455577432065/272343293457596426/unknown.png) 

Crusher : 
![2](https://cdn.discordapp.com/attachments/200785455577432065/272343351054041088/unknown.png) 

And also, pressing the button in the crate wont go to the next page 
![3](https://cdn.discordapp.com/attachments/200785455577432065/272343571712180235/unknown.png)

**Comment by Ellpeck** [comment] 2017-01-21 12:58
Try restarting your game or the server.
Also, I am closing this issue, as I don't support Sponge. Just use a normal Forge Server if the issue persists.

**Comment by canitzp** [comment] 2017-01-21 12:59
I experienced similar problems on a normal forge server, but I though it is a forge issue.

**Closed by Ellpeck** 2017-01-21 12:58 UTC

**Comment by Eufranio** [comment] 2017-01-21 13:01
On my server the bug is always there, all the times we open the GUI the buttons are red. Can you at least provide a bit more info about this error/bug instead ignoring a issue just because it contains the most used 1.10 server software environment?

**Comment by Ellpeck** [comment] 2017-01-21 13:01
The buttons are red because I made them red.
That's not an issue...
If they stop working, then *that's* an issue. And if it's only happening with Sponge and not with Forge, then this is not a problem on my side.

**Comment by Eufranio** [comment] 2017-01-21 13:06
We see that @canitzp may have the same issue, and its probably because of the *server* side, so I can't understand why you blame sponge. Why not be friends?

**Comment by Ellpeck** [comment] 2017-01-21 13:08
Please answer my question: Does reconnecting fix the issue, or does reconnecting not fix the issue?

**Comment by Eufranio** [comment] 2017-01-21 13:09
Does not fix the issue.

**Comment by Ellpeck** [comment] 2017-01-21 13:10
A lot of people have had this same issue, but I was never able to reproduce it. Talking to multiple people we have found out that this might be a Forge related issue, but with everyone else, including @canitzp, it was always easily fixed by just disconnecting and reconnecting to the server.
I have personally never managed to recreate the issue, so I never knew how I would be able to fix it.

**Comment by Ellpeck** [comment] 2017-01-21 13:10
Does restarting the server or anything else fix it, or is this a completely permanent issue?
If it doesn't fix it, please try to reproduce it outside a Sponge environment.

**Comment by Eufranio** [comment] 2017-01-21 13:11
Create a SpongeForge server with ActAdd and see yourself.

**Comment by Ellpeck** [comment] 2017-01-21 13:12
As I said, I don't support Sponge. If this is not recreatable outside of Sponge, then I don't care for this issue.

**Comment by Eufranio** [comment] 2017-01-21 13:13
Okay, thanks for your "support" anyway.

**Comment by HeyZeer0** [comment] 2017-01-21 13:28
So you're refusing to support the only and most used 1.10 modded server software? OMG...

**Comment by Eufranio** [comment] 2017-01-21 13:28
Unbelievable but yeah...

**Comment by canitzp** [comment] 2017-01-21 13:29
Only a hand full of modders are supporting sponge, asap

**Comment by Ellpeck** [comment] 2017-01-21 13:29
If you have a personal problem with my decision on that, then just don't use the mod.
Stop spamming the issue tracker about it, though. Thanks.

**Comment by canitzp** [comment] 2017-01-21 13:29
I currently investigating the problem on clean server, so wait for it.
Hint: Forge only with actadd works fine

**Comment by canitzp** [comment] 2017-01-21 13:39
https://github.com/canitzp/Modpack-Bugs/issues/3

please comment now here
