### ISSUE TITLE
Crash with latest Actually Additions and latest Forge on 1.12.

### ISSUE THREAD

**Issue by PurpleHel** [Ellpeck/ActuallyAdditions#1068] opened 2018-04-11 08:16 UTC
Minecraft 1.12.2
Forge 14.23.3.2657
Actually Additions 1.12.2-r133
Crash occurs with no other mods enabled, is fixed by reverting to Forge 14.23.2.2654

https://pastebin.com/Te5fyS8P

**Comment by MasterEnderman** [comment] 2018-04-11 13:51
I got another one: https://pastebin.com/2KayeD0X

**Comment by UpcraftLP** [comment] 2018-04-11 16:45
it's not an issue with actually additions, but with forge itself. had it also happen with thermal expansion and refined storage.

**Comment by malte0811** [comment] 2018-04-11 17:03
Linking to BluSunrize/ImmersiveEngineering#2934 since it's probably caused by the same problem. I might try to debug this later today.

**Comment by Shadows-of-Fire** [comment] 2018-04-11 17:09
I'm debating if I should report this to forge...

**Comment by malte0811** [comment] 2018-04-11 18:06
Some news
 - This is definitely caused by capabilities not being initialized properly. I tested with the energy cap, no mods except forge (only modification to Forge was inserting a null-check after the capability initialization).
 - It only happens in a normal MC client, not a Forge dev environment (as in a environment for making Forge PR's, not an MDK. No idea whether those crash). I don't think it's because of obfuscation, the relevant classes shouldn't be obfuscated and the commits that broke it aren't obfuscation related as far as I can see. This is a bit inconvenient since making a forge build takes about 9 minutes for me.

**Comment by malte0811** [comment] 2018-04-11 19:14
MinecraftForge/MinecraftForge#4865
I guess this can be closed now, it's definitely a Forge issue.
@PurpleHel @MasterEnderman downgrade Forge to the recomended version (2654), that should fix it.

**Comment by Shadows-of-Fire** [comment] 2018-04-11 19:15
I'll keep it open to prevent duplicates being opened.  I'll close it when 4865 is closed

**Closed** 2018-04-11 22:45 UTC

**Comment by Morpheus1101** [comment] 2018-04-14 06:52
May i suggest ya change the subject of this crash to specify it occurs on *.2657 of Forge as saying "Latest" is a lil ambiguous
