### ISSUE TITLE
Negative Energy in GUI

### ISSUE THREAD

**Issue by MrRiegel** [Ellpeck/ActuallyAdditions#320] opened 2016-11-04 16:51 UTC
![2016-11-04_17 48 32](https://cloud.githubusercontent.com/assets/13290261/20014403/20dfb59e-a2b7-11e6-831b-fb34d8141cdf.png)

after inserting some stuff into the reactor it is fine

**Comment by canitzp** [comment] 2016-11-04 17:21
I have seen something in other mods, like Cyberware. Maybe it is a minecraft/forge syncing issue

**Comment by Ellpeck** [comment] 2016-11-04 20:28
Is it the syncing or the actual energy amount? Don't really know how you'd figure out, but maybe you did.

**Comment by Ellpeck** [comment] 2016-11-04 22:23
Please try to reproduce this with just Actually Additions installed.

**Comment by MrRiegel** [comment] 2016-11-06 18:39
Sorry, I can't even reproduce it with other mods.
Maybe the problem only on servers.

**Comment by Ellpeck** [comment] 2016-11-06 19:03
It's never happened to me before. Does it happen with other blocks?

**Comment by canitzp** [comment] 2016-11-06 19:06
TUMAT has shown such things in my HL2 modpack at the Cyberware charger

**Comment by Ellpeck** [comment] 2016-11-07 06:56
Closing this as it doesn't appear to be caused by Actually Additions.

**Closed by Ellpeck** 2016-11-07 06:56 UTC
Labels: bug, minor, waiting
