### ISSUE TITLE
Double crasher and Powered Furnace bug

### ISSUE THREAD

**Issue by jimozzo** [Ellpeck/ActuallyAdditions#270] opened 2016-10-06 11:12 UTC
Double crasher and Powered Furnace doesn't accept energy from mekanism cable i tried puttin in all sides but nothing  i'm using r65 version

**Comment by Ellpeck** [comment] 2016-10-06 14:14
Just use different cables for now, Mekanism doesn't really seem like it's stable as there were a lot of bugs that weren't caused by Actually Additions in the past. 
This particular one I am going to have to check though.

**Comment by jimozzo** [comment] 2016-10-07 08:39
ok thanks oh another thing to mention cable do attach to the machine but rf don't come :D

**Comment by Ellpeck** [comment] 2016-10-07 20:02
Does this occur with any other RF/Tesla mods?

**Comment by jimozzo** [comment] 2016-10-08 08:22
i tried with ender io cable and is working  probably is a mekanism problem i suppose

**Comment by Ellpeck** [comment] 2016-10-08 08:46
Huh. I can't seem to find the source of it either, but it is indeed reproducable. It might be best if you also report this to Mekanism and see if they can find a solution. Please mention this issue then, too. :)

**Comment by Tsukiumy** [comment] 2016-10-15 03:39
just to confirm, but you changed the cables to input mode with the configurator?, i remember some machines needed this tipe of trick to work.

**Comment by Ellpeck** [comment] 2016-10-19 14:30
I'm going to close this for now.

**Closed by Ellpeck** 2016-10-19 14:30 UTC
Labels: bug
