### ISSUE TITLE
Automatic Precision Dropper Bug !!!

### ISSUE THREAD

**Issue by BuKa33** [Ellpeck/ActuallyAdditions#879] opened 2017-08-05 22:30 UTC
i m using ActuallyAdditions-1.11.2-r110. When I put redstone into it, it keeps throwing redstone. it is unlimited. please look at it.

**Comment by SpectacularNumbers** [comment] 2017-08-05 22:31
Dupe of #747.

**Comment by Shadows-of-Fire** [comment] 2017-08-05 22:43
1.11 is not supported

**Closed by Shadows-of-Fire** 2017-08-05 22:43 UTC
