### ISSUE TITLE
phantom energyface not charging blocks next to it

### ISSUE THREAD

**Issue by LocoMinerDad** [Ellpeck/ActuallyAdditions#532] opened 2016-12-25 21:22 UTC
I have a phantom energyface next to a energizer and the energizer isnt being charged. The phantom says its connected to my energy relay. Am I missing some pieces?

**Comment by Ellpeck** [comment] 2016-12-25 21:24
Post a screenshot of your setup.

**Comment by LocoMinerDad** [comment] 2016-12-25 21:40
![2016-12-25_13 39 46](https://cloud.githubusercontent.com/assets/11432217/21472984/b89eb732-caa7-11e6-8bbb-6d331c18da88.png)
Relay is off screen

**Comment by tigier** [comment] 2016-12-25 21:44
You use the system the wrong way around

**Comment by tigier** [comment] 2016-12-25 21:44
The face is the transmitter not the receiver

**Comment by Ellpeck** [comment] 2016-12-25 21:44
Relay is the important part that I need to see though..

**Comment by Ellpeck** [comment] 2016-12-25 21:44
And no, what tigier is saying is incorrect. This system should work both ways.

**Comment by tigier** [comment] 2016-12-25 21:46
The last time I tried to use it it only worked one way for me.....Maybe I did something wrong back then....My apologies

**Comment by LocoMinerDad** [comment] 2016-12-25 21:52
OK so is this being fixed? Which way is it suppose to be? Please give an example of correct usage.

**Comment by Ellpeck** [comment] 2016-12-25 21:55
It is supposed to work both ways.
Please post the other side of your setup as well, this one screenshot doesn't help me much right now.

**Comment by LocoMinerDad** [comment] 2016-12-25 22:04
other side? you mean the energy relay?

**Comment by LocoMinerDad** [comment] 2016-12-25 22:07
![2016-12-25_14 05 00](https://cloud.githubusercontent.com/assets/11432217/21473030/36e64ce2-caab-11e6-91c8-e06342b8ea9a.png)
your mods heat collector etc connected to energy relays connected to phantom block.

**Comment by Ellpeck** [comment] 2016-12-25 23:56
If you connect the same Phantomface to any other energy outputting machine, will that transmit like it should?

**Comment by LocoMinerDad** [comment] 2016-12-26 14:03
I replaced the energizer that is right of the phantom with a coal generator. The generator is making power and the atomic above the phantom isn't being charged.

**Comment by Ellpeck** [comment] 2016-12-26 16:34
"If you connect the same Phantomface to any other energy outputting machine" = The Phantomface should display "Connected to Coal Generator" or something like that.
Connected, not "next to". ;)

**Comment by Ellpeck** [comment] 2016-12-26 16:39
Because if every block works besides the Energy Laser Relay, this is not a bug. The Relays' functionality is just completely different from most other blocks and so they can't really transmit through Phantomfaces. 
The way this could work, though, is by placing the Phantomface next to the Relay and then connecting it to a power storage block somewhere else, so the other direction.
This behavior should be exclusive to Laser Relays though.

**Comment by LocoMinerDad** [comment] 2016-12-26 18:27
I don't understand. I connected a generator to the Phantom and it didn't charge any blocks around it or to all those farmers. Your reply makes to sense to me. It's not sending or receiving energy and you say it's not a bug.

**Comment by Ellpeck** [comment] 2016-12-26 18:45
![2016-12-26_19 39 20](https://cloud.githubusercontent.com/assets/5741138/21485396/1c0fe7c2-cba3-11e6-8b4e-0ba0a8d062c5.png)
These are four horizontal setups. From top to bottom:
1. Coal Generator outputting into a Phantomface, the latter connected to a Crusher - working.
2. Coal Generator connected to a Phantomface, the latter outputting into a Crusher - working.
3. Laser Relay connected to a Phantomface, the latter outputting to a Crusher - not working.
4. Laser Relay outputting into a Phantomface, the latter connected to a Crusher - working.

This is expected behavior. The reason 3. is not working is that Laser Relays themselves don't actually *store* any power, they just try to output energy that they receive through any power producing blocks connected to other Laser Relays in the network into all of the blocks directly adjacent to them on all the six sides.
The Phantomface, however, doesn't really "know" about this network behavior, meaning it will never try to output any energy - because it doesn't directly receive energy.

What this means: You can only connect a Phantomface to any power outputting block that also stores this power in one way or another, which is not a feature of Laser Relays.
Something like EnderIO conduits, however, actually have an internal per-block storage of about 100 units, which is why connecting a Phantomface to those works.

If this is the behavior you are experiencing, please close this issue. If not, you will have to explain your issue further.

**Comment by LocoMinerDad** [comment] 2016-12-26 19:13
I thought the Phantom blocks were suppose emit power when connected to a relay or power source.  I think they look nicer than the relays. It sounds like they don't do that. If this is correct I'll put the relay back to power those 4 machines and move on.

**Comment by Ellpeck** [comment] 2016-12-26 19:14
I explained in the last comment the behavior of Laser Relays compared to the behavior of other power sources. 

I take this as you confirming the behavior is as in my explanation above and I will close this issue.

**Closed by Ellpeck** 2016-12-26 19:14 UTC
Labels: bug, investigate
