### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by kellixon** [Ellpeck/ActuallyAdditions#1165] opened 2018-08-17 13:14 UTC
MC 1.12.2. ActuallyAdditions r140.
Crash reports - https://gist.github.com/kellixon/a562af84230ea33300101b9ea3cf6507

**Comment by Matchyman** [comment] 2018-08-17 14:20
Also having this issue 
https://pastebin.com/UNv0sx30

**Comment by Matchyman** [comment] 2018-08-17 14:47
i also had this problem are you using the newst enderio core that is in alpha? If so, go back one version to the realse one and it will all work fine :D

**Comment by Shadows-of-Fire** [comment] 2018-08-17 16:55
Duplicate of #1162

**Closed by Shadows-of-Fire** 2018-08-17 16:55 UTC
