### ISSUE TITLE
Startup crash with a different client but same files

### ISSUE THREAD

**Issue by DrKilledalot** [Ellpeck/ActuallyAdditions#1069] opened 2018-04-12 00:42 UTC
We startet a server with a custom modpack/config  , server runs fine, and after uploading the files for distribution evryone till now had no problem using the pack/playing on the server 
but now someone (seemingly) at random crashes evrytime after the startup loaded to 100%

heres the report: https://pastebin.com/LnYkiJ1t

**Comment by Shadows-of-Fire** [comment] 2018-04-12 01:09
duplicate of #1068 
`don't use forge 2657`

**Closed by Shadows-of-Fire** 2018-04-12 01:09 UTC
