### ISSUE TITLE
rotten flesh to leather

### ISSUE THREAD

**Issue by sandje1976** [Ellpeck/ActuallyAdditions#335] opened 2016-11-06 17:59 UTC
my atomic reconstructor used to turn rotten flesh into leather but now it doesnt do that anymore....i have enough RF for my machines. Thx in advance

**Comment by tigier** [comment] 2016-11-06 18:04
With these informations it will probably will be complicated to locate the problem. An advanced description of your reconstructor setup or screenshots might help.

**Comment by Ellpeck** [comment] 2016-11-07 19:13
Can't reproduce this.

**Comment by Inve1951** [comment] 2016-11-10 12:58
i had the same issue, sometimes it just won't work
retrying at a later moment it worked as it should
had the same with other reconstructor recipes too

**Comment by Ellpeck** [comment] 2016-11-10 13:01
Do you have the required amount of energy though, and is it in the area? I can't reproduce this.

**Comment by YasminEndusa** [comment] 2016-11-10 13:06
At those who have the problems: i've often seen people putting the items directly infront of the reconstructor, thinking it transforms whatever items it hits. This is not the case (as stated in the manual). Please make sure that the items are on a block that is directly touching the last block the beam of the reconstructor hits. If the problem persists, please make sure to attach screenshots or maybe even a video. That would help tremendously.

**Comment by danielhickman** [comment] 2016-11-10 21:01
Try with one flesh where the laser hits a block. It uses a lot of power and it won't do a reconstruction unless it has enough power to do all of them it seems. I can only do 9 nether quartz or 37 zombie flesh at a time when full even with top tier EnderIO cables. If I'm correct I'd like to propose Botania-like mechanic where it does the max it can do and waits until it has more mana [power]. A cool down on the dropped items would also be cool so you can pick up the leather without picking up the flesh.

**Comment by Ellpeck** [comment] 2016-11-10 21:07
It does that already. Update the mod.

**Comment by danielhickman** [comment] 2016-11-11 02:23
If it is in revision 70 and not 69, I can't wait! :D

**Comment by Ellpeck** [comment] 2016-11-13 14:51
What's the deal with this now? Can anyone reproduce it? If so, do a video please. :v

**Comment by Inve1951** [comment] 2016-11-13 18:55
i'm unable to reproduce it and also yasmin might be right in that the items might have been missplaced tho i do think everything was set up correctly
i do know for sure that the reconstructor was at full charge and the laser went out when i gave it the signal (button); i could shoot multiple lasers at the same entity and it wouldn't have any effect
i do not remember if the white particles showed up or not

**Comment by Ellpeck** [comment] 2016-11-13 18:58
I'm going to close this for now then, appears to have just been the misplaced items. If the issue reoccurs, just reopen this! :D

**Closed by Ellpeck** 2016-11-13 18:58 UTC
Labels: bug, investigate, waiting

**Comment by sandje1976** [comment] 2016-11-17 19:47
i think i solved it, i cant throw a whole stack at a time, only like 5 or 6
but thats ok, works for me..thank you everyone for the help :D
