### ISSUE TITLE
[1.10.2-r98] - Crash with custom config and latest ZeroCore

### ISSUE THREAD

**Issue by MasterFee** [Ellpeck/ActuallyAdditions#646] opened 2017-02-17 14:16 UTC
Minecraft crashes while loading the mods after I update ZeroCore (library for Extreme Reactors). Latest version being 0.1.0.3.
Only thing I changed was disabling stuff like Solidified XP or the Coffee Maker. Tried removing the edited config and it worked fine. I also tried to downgrade ZeroCore which seems to solve the problem as well. Reported the crash to ZeroCore developer too - he stated that his mod isn't causing the problem. 

Config:
http://pastebin.com/hZG5Sybc
Crash report:
http://pastebin.com/5AkxRmJK

**Comment by Ellpeck** [comment] 2017-02-17 14:18
This bug has been fixed in dev.
It is caused by a broken furnace recipe in the furnace recipe registry that either doesn't have an input or an output item.
Does removing ZeroCore or Extreme Reactors fix the problem? If so, please report what I said to them.

**Comment by MasterFee** [comment] 2017-02-17 14:20
Yes removing or downgrading it fixes the problem

**Comment by ZeroNoRyouki** [comment] 2017-02-17 16:41
Hi there

I just tested this again with only Zero Core (that does not add any smelting recipe) 1.10.2-0.1.0.3, Extreme Reactors 1.10.2-0.4.5.26 and Actually Additions 1.10.2-r98

No crash

![2017-02-17_17 37 58](https://cloud.githubusercontent.com/assets/7107662/23074064/efc2b51e-f537-11e6-9ad9-3ad6b4801f43.png)

I've also checked the internal data of the furnace recipes list and there are no null inputs/outputs

My guess is that another mod messing around with the furnace recipes or with vanilla items (I use coal in one recipe for example) or our ones

**Comment by MasterFee** [comment] 2017-02-17 17:50
Alright after disabling and enabling almost every mod in my mod pack I came to the conclusion that Ex Nihilo Adscensio and maybe Ex Compressum are causing the issue

**Comment by Ellpeck** [comment] 2017-02-17 21:04
I'm closing this for now as it seems unrelated.
If it turns out to actually be realted to Actually Additions, please reopen the issue.

**Closed by Ellpeck** 2017-02-17 21:04 UTC
Labels: investigate
