### ISSUE TITLE
Item duping bug

### ISSUE THREAD

**Issue by mcnubblet** [Ellpeck/ActuallyAdditions#151] opened 2016-07-13 10:27 UTC
I have a sorting system based on advanced item laser relays ending with a catch all item laser relay (not advanced).  When I put a single item into the system that is not caught by the sorter, I get 1 stack (sometimes 2) of the item in the reject chest attached to the catch all item laser relay.

**Comment by Ellpeck** [comment] 2016-07-13 10:31
Can't reproduce.

What Minecraft version?
What other mods installed?
What type of chest?
Give me some helpful information please.

**Comment by mcnubblet** [comment] 2016-07-13 11:31
MC: 1.10.2
Other mods:
EnderBags-1.9.4-2.0.0.jar
jei_1.10.2-3.7.3.221.jar
Ping-1.10.X-1.2.2.B7-universal.jar
teleporters-1.1.3.jar
thutcore-1.9.4-3.1.8.jar
thuttech-3.0.5.jar
ActuallyAdditions-1.10.2-r49.jar

Type of chest is a small crate.

Happy to upload the world somewhere for you if you would like.

**Comment by Ellpeck** [comment] 2016-07-13 11:35
Still can't reproduce.
What are you inputting with?

**Comment by mcnubblet** [comment] 2016-07-13 11:45
input is a small crate -> esd -> item interface -> item laser relay -> advanced item laser relay ......... -> item laser relay small crate.

the chain AILR chain looks like:
```
SC <- ILR -------          AILR -> AILR -> AILR -> ....
                 \           ^       v       v
                  \        AILR    AILR    AILR
                   \         ^       v       v
SC -> AESD -> II -> ILR -> AILR    AILR    AILR
```

**Comment by Ellpeck** [comment] 2016-07-13 11:55
Yea I don't get what you're saying.
Please just make a video or a couple of screenshots.

**Comment by mcnubblet** [comment] 2016-07-13 12:08
http://imgur.com/a/ONxnX

**Comment by Ellpeck** [comment] 2016-07-13 12:44
If you disconnect the ESD from the relay above it and move them a block apart, does it stop happening?

**Comment by mcnubblet** [comment] 2016-07-13 13:14
Yes, your suggestion has stopped the behavior. Cheers.

**Comment by Ellpeck** [comment] 2016-07-13 13:21
Yeah, it's still a bug that I don't understand.
Dang it.
I'll close this for now but I'll keep it in mind.

**Closed by Ellpeck** 2016-07-13 13:21 UTC
Labels: wat
