### ISSUE TITLE
[r85] Crossmod issue with Integrated dynamics

### ISSUE THREAD

**Issue by Belgabor** [Ellpeck/ActuallyAdditions#431] opened 2016-12-03 03:32 UTC
I found a slightly annoying cross-mod bug with integrated dynamics. If you break a cable from Integrated Dynamics with the drill any cable attachments (readers, writers etc.) vanish.
A regular pick only breaks the part you target and leaves the attachments (or cable, if you target an attachment) intact, but the drill breaks the whole block and only gives you the cable.

**Comment by Ellpeck** [comment] 2016-12-03 09:17
Hey @rubensworks, is this on my side or on yours? :v
I cobbled together [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/util/WorldUtil.java#L320) method for breaking blocks once, it's half Tinkers' Construct's way of breaking blocks and half just copied from PlayerInteractionManager. But it might be outdated or something.

**Comment by rubensworks** [comment] 2016-12-03 14:57
Your harvesting code looks fine to me.

What happens if you mine an MCMP part? Does it break the whole block as well?
Because the code behind ID part breaking is very similar to that of MCMP, but it's possible that I missed some edge cases...

**Comment by Ellpeck** [comment] 2016-12-03 15:53
I have no idea actually. @Belgabor, it'd be useful if you could also try that if MCMP is part of your modpack :)

**Comment by Belgabor** [comment] 2016-12-03 17:39
Ok, I can only check it with the ID cables and C&B bits, but yes, the drill breaks all but in that case I get everything, both the cable and the C&B block.

**Comment by Ellpeck** [comment] 2016-12-03 17:48
Can you compare to something like the AOE Mining of the TiCon hammer? 
Meaning, break the cables and/or C&B Bits but not by aiming the tool directly at them, but onto the block next to them.

**Comment by Ellpeck** [comment] 2016-12-03 17:49
Oh and @rubensworks, I know they probably don't use the same system, but I know that the Drill breaks EnderIO conduits right, meaning they will break only the one you look at if you have multiple ones in one block.

**Comment by Belgabor** [comment] 2016-12-03 18:48
Ok.. this is interesting.
I added the mods to my test instance, what happens with a TiCo Hammer (cobalt) is this:

|Block broken|A|B|C|
|--------------|---|---|---|
|Stone next to everything|cable gone, importer intact|cable gone|ignored|
|just cable (B)|cable gone, importer intact|cable broken & recovered|ignored|
|cable in A|cable broken & recovered, importer intact|cable gone|ignored|
|importer in A|importer broken & recovered, cable intact|cable gone|ignored|

A: cable and importer
B: just cable
C: cable & some bits

The drill, now that I tested in more detail, recovers the part you are targeting in A and destroys the other part. With the 3x3 augment it does not break any cables in adjacent blocks

**Comment by Ellpeck** [comment] 2016-12-03 19:31
So.. Chisels and Bits stuff works fine and as intended, but cable doesn't?

**Comment by Belgabor** [comment] 2016-12-03 20:43
Yes and no if you are talking about the drill. A pick can break the individual parts (aka either the cable or the C&B part), the drill breaks the whole block. But with C&B + cable you get everything, so it is not destroying anything.

**Comment by Ellpeck** [comment] 2016-12-03 20:52
Yea, okay. But with the cable alone, it's @rubensworks' fault then.
Yay, finally able to blame someone \o/
No, but really. I have no idea what causes this. You should probably check your stuff too though. Or maybe I should. I don't know.

**Comment by rubensworks** [comment] 2016-12-04 07:49
I'll have to look into this.

@Belgabor Could you open an issue at the ID repo for this? Just so I don't forget, because I won't have time to fix this any time soon.

@Ellpeck Could you provide me with a deobfuscated build of AA? That might make debugging this a bit easier.

**Comment by Ellpeck** [comment] 2016-12-04 09:47
The Jenkins and Maven are linked in the README, but you can also just use a regular build in your dev environment since 1.8.

**Comment by Ellpeck** [comment] 2016-12-04 21:38
I will close this as it appears to be a bug with Integrated Dynamics :)

**Closed by Ellpeck** 2016-12-04 21:38 UTC
Labels: bug, investigate, waiting
