### ISSUE TITLE
Relays get disconnected

### ISSUE THREAD

**Issue by Teyrin** [Ellpeck/ActuallyAdditions#696] opened 2017-03-17 18:31 UTC
After setting up a large Relay and item sorter my mobs get really slow (instead of moving smooth the lag/rubberband around the map, A.I. initiating really late e.t.c.. The most annoying is that my Relays get disconnected at random, this goes for Advanced Item, Item, Power and Advanced Power relays. It is really annoying and I figured it would be related, do you know a reason/fix or is there a maximum of relays my PC can handle? (It is a single player game).

![Uploading Item sorting.png…]()

**Comment by Ellpeck** [comment] 2017-03-17 18:48
Please send a screenshot of your setup and a copy of the world.

**Comment by Teyrin** [comment] 2017-03-17 19:04
I am new to github, and my Screenshot didn't upload, how do I upload these from my PC?

**Comment by Ellpeck** [comment] 2017-03-17 19:09
Just use a sharing site like http://dropbox.com :)

**Comment by Teyrin** [comment] 2017-03-17 19:46
The world Save (Water World), Mod folder (1.11.2) and several screenshots of the house (just linked all the relays again)
https://www.dropbox.com/sh/66tg9if54yfi6i9/AABhvTVyqzzA8xu60NQFwCqsa?dl=0

**Comment by Ellpeck** [comment] 2017-03-17 20:26
The AI slowing down is a byproduct of the fact that you have a lot of item lasers connected to a lot of inventories. Every time an item is input into the system, it loops through all of the inventories to try to find a slot, all in one tick. This creates more lag the more chests you add, but can get pretty bad with this many chests. 
However, I cannot do anything about that as this is just the way item handling works. A way to fix this would be using less big chests (or less chests in total) to store your stuff.

The disconnection issue on the other hand seems weird. When exactly are they disconnecting? Is it when (re-)loading the chunks, or when quitting the world, etc?

**Comment by Teyrin** [comment] 2017-03-17 20:32
I think it happens when I reload chunks and disconnect from game, I don't really notice until the sorting chest (near the Powered Furnaces and stuff) doesn't flow through, I check which item clogs it and check the connections. I noticed it most when I went out Mining and then get back, but it can also be an older disconnect after the world was reloaded.

As for fixing the lag, the best way would then be to make the farms only connected to the energy generators, so that one only checks small chests and the auto sorter only needs to check when used after adventuring/mining. I will try this to see if it helps :-) Thx for that hint

**Comment by Ellpeck** [comment] 2017-03-17 21:08
Does it always break the exact same connections?
Could you try connecting a bunch of lasers in a creative world and see if you can reproduce the disconnection issue?

**Comment by Teyrin** [comment] 2017-03-17 21:11
It is random, I have had old and new ones diconnected, the first time I noticed where the ones on the farms.

I will start a new world in Creative and see if I can reproduce the problem.

**Comment by Ellpeck** [comment] 2017-03-17 21:11
Thanks. You doing some investigating is a big help <3

**Comment by Teyrin** [comment] 2017-03-17 22:56
I haven't been able to reproduce the problem on another save. I will check in game if I can pinpoint the problem. For now I will at least Modify the relay network to release the load on the ticks, maybe it is related to that, as the item interface does not update automatically as well, I need to re-target the ESD (exceptionally strange device?) from and to the Item Interface to update the item slots, I will be adding a Mob Grinder, so if it worsens I will update you on it in this threat.

Thanks for the help, I will keep you posted, I may even start a new world and see if it happens again.

**Comment by Ellpeck** [comment] 2017-03-18 01:32
I'll close this for now as it seems to be a one-time exception, maybe related to some issue inside of your world.
Just reopen the issue if you find out more :)

**Closed by Ellpeck** 2017-03-18 01:32 UTC
Labels: investigate

**Comment by darkshadow543** [comment] 2017-04-01 18:40
What are the coords of your base?
