### ISSUE TITLE
crate small to medium upgrade destroys content

### ISSUE THREAD

**Issue by dhalek** [Ellpeck/ActuallyAdditions#917] opened 2017-09-08 18:19 UTC
With Minecraft 1.12.1 and Actually Additions 1.12.1-r119 when applying a crate upgrade to a small crate just the top line of slots keep their content. Also the crate upgrade is not consumed in the process.

**Comment by Shadows-of-Fire** [comment] 2017-09-08 18:21
Duplicate of #911

**Closed by Shadows-of-Fire** 2017-09-08 18:21 UTC
