### ISSUE TITLE
[1.9] Spawner changer not working correctly.

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#95] opened 2016-05-19 01:39 UTC
Forge 1900
ActuallyAdditions-1.9-r33

Grabbed an Enderman with the spawner changer, changed a zombie spawner with it and it changed to an enderman spawner.  Spawned 1 enderman then reverted back to a zombie spawner.

Is this a bug or by design?

**Comment by Ellpeck** [comment] 2016-05-20 18:35
Can't reproduce.
Any more details?

**Comment by DoomSquirter** [comment] 2016-05-20 19:27
So, I was the one that originally had the issue but b0bst3r was nice enough to create the ticket.  

After some testing, I think it might be quantum flux matter transporter that might be causing the issue.

In this world, I haven't been able to find a vanilla dungeon so all zombie spawners are taken from ruins mod which shouldn't change nbt on the spawners.  The blaze spawner however is vanilla.

* moved zombie spawner, applied enderman spawn changer to it, made one enderman, reverted back to zombie spawner. (above issue)
* moved blaze spawner, applied enderman spawn changer to it, made one enderman, reverted back to blaze spawner.
* moved zombie spawner to nether, applied skeleton spawn changer to it, made one wither skeleton and reverted back to zombie spawner.
* A friend applied a skeleton spawn changer directly to a blaze spawner tho, without moving it, and it stayed a skeleton spawner, spawning wither skeletons.

So, that's the only information I have at the moment but the only thing I can conclude is moving the spawner before hand causes the spawner to revert back to what it was prior to adding the spawn changer.

**Comment by Ellpeck** [comment] 2016-05-20 19:52
Huh, this is very odd. It seems to work for me. Please try to reproduce it with just Actually Additions installed. 
If it then still occurs or you actually find the mod that probably causes this, if it's not vanilla or ActAdd itself, please reopen the issue :)

**Closed by Ellpeck** 2016-05-20 19:52 UTC
Labels: bug, investigate
