### ISSUE TITLE
[1.12.1] CTD when putting gravel ore in Grinder

### ISSUE THREAD

**Issue by Nargath** [Ellpeck/ActuallyAdditions#907] opened 2017-08-24 02:46 UTC
Mod Version: 1.12-r118
Forge: 14.22.0.2459
Simple Gravel Ores version: 1.7b
Crash Log: https://pastebin.com/Xx6pawB9

When I put a stack of copper gravel ore from the Simple Gravel Ores mod into my Grinder, it crashed to desktop. Normal ores worked fine prior to this.

While it may not go in there, it also probably shouldn't crash the game :P

**Comment by Shadows-of-Fire** [comment] 2017-08-24 02:49
Duplicate of #904

**Closed by Shadows-of-Fire** 2017-08-24 02:49 UTC
