### ISSUE TITLE
Crash when placing down fermenting barrel

### ISSUE THREAD

**Issue by KristjanKr** [Ellpeck/ActuallyAdditions#437] opened 2016-12-03 11:10 UTC
Minecraft version: 1.10.2
ActuallyAdditions version: ActuallyAdditions-1.10.2-r85
Forge: build 2171

Crash log: http://paste.ee/p/5D9mZ

What happens?: When placing down fermenting barrel the game crashes completely and gives crash log which hopefully helps you.

What should happen instead?: Place fine without crashing.

**Comment by Ellpeck** [comment] 2016-12-03 11:28
Does it happen every time?

**Comment by Ellpeck** [comment] 2016-12-03 11:34
Please tell me this only happened once and you can't reproduce it so that I don't have to release another bugfix update for 1.10 :^)

**Comment by KristjanKr** [comment] 2016-12-03 12:07
It sadly doesn't happen only once and i can reproduce it.. It would be awesome if you could release bugfix release. Also off-topic but will you drop 1.10.2 support soon and just continue developing for 1.11?

**Comment by Ellpeck** [comment] 2016-12-03 12:14
I can't reproduce this.
Please turn on F3+H and the Advanced Item Info in the config GUI if it's turned off, hover over the Fermenting Barrel in question and press Shift+CTRL and make a screenshot.
It shouldn't happen with any other barrels, right?

**Comment by KristjanKr** [comment] 2016-12-03 12:35
I did see that you fixed it for 1.11 build, im playing on 1.10.2 tho, so if you made build for that i could test it out if it stops crashing, also if it helps then the fermenting barrel was placed down next to canola press when it crashed. Also this crash duplicated fermenting barrel. For me this crash happens every time.
Also here's the screenshot:  http://imgur.com/a/PB1ot
The duped fermenting barrel screenshot: http://imgur.com/a/vqrWZ

**Comment by KristjanKr** [comment] 2016-12-03 12:36
Extra info: placing down the duped fermenting barrel does not crash the game, only the faulty one(which on crashing dupes into the other barrel)

**Comment by Ellpeck** [comment] 2016-12-03 12:38
Please post a screenshot of the setup. I still can't reproduce this.

**Comment by Ellpeck** [comment] 2016-12-03 12:39
This might seem really random, but try without OptiFine and see if that fixes it.

**Comment by KristjanKr** [comment] 2016-12-03 12:42
Umm what has optifine to do with this problem? as far as i remember optifine doesnt touch recipes which give probably broken fermenting barrel that crashes the game due to missing nbt tag, which seems to be the case here. http://imgur.com/a/ckP4A This setup used to crash me everytime, until i placed down the duplicated barrel instead of placing down the faulty one: http://imgur.com/a/PB1ot

**Comment by Ellpeck** [comment] 2016-12-03 12:43
Optifine has the ability to bug out everyone and everything. So please try removing it.

**Comment by Ellpeck** [comment] 2016-12-03 12:46
The commits I did wouldn't have changed anything. If an NBT Tag isn't found, it just returns a new, empty one. There's nothing that can be missing here.
If OptiFine doesn't fix it, try removing all other mods and see if that fixes it.

**Comment by KristjanKr** [comment] 2016-12-03 13:18
Hmm that is weird because if i placed down the problematic barrel(it has no nbttag) then it crashes the game and if i open minecraft again and open my single player world again, there's a fermenting barrel placed. Now when i break it, i get the barrel which has nbttag oiltank empty or smth like that(http://imgur.com/a/ZWjYm) and that does not crash the game. So the commits you did would probably still crash the game. Removing optifine still causes still crash: http://paste.ee/p/onZg4 
Removing all other mods fixes this crash if only mod lodded with forge is actuallyadditions and nothing else.

**Comment by Ellpeck** [comment] 2016-12-03 13:19
Okay. Please try to find out which mod is required for the crash to happen. It's best if you add them in big bunches at first and then try to scale it down to a single one.

**Comment by KristjanKr** [comment] 2016-12-03 14:21
This is really big pain when the crash log says nothing about which mod could cause this. If this helps then here is my modlist: http://paste.ee/p/rslXc I sadly do not have time to go thru the whole modlist myself, as im extremely busy with studies and have to catch up with school.

**Comment by Ellpeck** [comment] 2016-12-03 14:42
If this ever happens to anyone again, I will do further investigation. For now, I'll just declare it a weird thing about Minecraft.
You said it only happens with that one Fermenting Barrel, but no other ones, right?

**Comment by KristjanKr** [comment] 2016-12-03 14:45
To be exact it happens with every freshly crafted fermenting barrel, when you place it down and crash once, then you see that the fermenting barrel was actually placed and when you break it and then put that back down, you won't crash. Weird thing indeed.

**Comment by Ellpeck** [comment] 2016-12-03 15:52
But you need to try to find out which mod does it yourself, because I am unable to reproduce this issue.
And other users appear to also not have this, because there's never been a report.

**Comment by uecasm** [comment] 2016-12-04 01:52
FWIW, this exact thing happened to me too.  Using the DW20 1.10 pack, placing a newly crafted fermenting barrel directly between an Oil Generator and a Canola Press, both of which were completely full of canola oil.  Then this happens:

````Time: 12/3/16 10:17 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.fluids.FluidTank.readFromNBT(FluidTank.java:61)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityFermentingBarrel.readSyncableNBT(TileEntityFermentingBarrel.java:67)
	at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.func_180633_a(BlockContainerBase.java:219)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:171)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:463)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

actuallyadditions{1.10.2-r85} [Actually Additions] (ActuallyAdditions-1.10.2-r85.jar) 
````

Restarting after the crash, there is a placed barrel in the world and I have a dupe in my inventory.  The in-world one seemed to work after that and I didn't try reproducing the crash.

**Comment by Ellpeck** [comment] 2016-12-04 02:00
Try updating to the newest version of Actually Additions. Does it still happen then?

**Comment by Schwantastic** [comment] 2016-12-04 04:30
Hi, same issue here in my own private mod pack. I placed the barrel and crashed. Upon loading the world again the barrel was placed and I had one in my inventory.  Placing another one caused a crash again. I'm on 1.10.2 latest update. Same log as uecasm.

**Comment by uecasm** [comment] 2016-12-04 04:56
I couldn't reproduce it in a test world after updating to r87, but also couldn't reproduce it after downgrading to r85 again, so I'm not sure.  I tend to keep my mods updated so it's possible updating something else fixed it as well, or just that there's something else required to trigger it that I didn't manage to replicate in the test.

**Comment by Schwantastic** [comment] 2016-12-04 05:33
I will try soon with updated mods and see if I crash again.   If so I'll try to single a mod causing the problem.  If it's a mod, that is

**Comment by Schwantastic** [comment] 2016-12-04 06:22
Seems to be fixed.   Only change was an update to quark.

**Comment by Ellpeck** [comment] 2016-12-04 09:46
I am going to close this as it seems to be fixed through the change then.

**Closed by Ellpeck** 2016-12-04 09:46 UTC
Labels: bug, investigate, waiting
