### ISSUE TITLE
Greenhouse Glass that is speeding up a Sapling (specifically Oak) crashes the game

### ISSUE THREAD

**Issue by kenlauescuadro** [Ellpeck/ActuallyAdditions#1197] opened 2018-10-22 11:18 UTC
AA Version: 1.12-r141

Something about seeing "Greenhouse Glass" and "Sapling" made me think of the conclusion (in the title).

Here's an error.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
  LoadingPlugin (Quark-r1.5-129.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 10/22/18 5:02 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=stage, clazz=class java.lang.Integer, values=[0, 1]} as it does not exist in BlockStateContainer{block=minecraft:log, properties=[axis, variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:66)
	at net.minecraft.block.BlockSapling.func_176474_b(BlockSapling.java:232)
	at de.ellpeck.actuallyadditions.mod.blocks.BlockGreenhouseGlass.func_180650_b(BlockGreenhouseGlass.java:86)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:66)
	at net.minecraft.block.BlockSapling.func_176474_b(BlockSapling.java:232)
	at de.ellpeck.actuallyadditions.mod.blocks.BlockGreenhouseGlass.func_180650_b(BlockGreenhouseGlass.java:86)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: World #1
	All players: 1 total;
	Chunk stats: ServerChunkCache: 471 Drop: 0
	Level seed: -323795377419288283
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1161,72,-1266), Chunk: (at 7,4,14 in -73,-80; contains blocks -1168,0,-1280 to -1153,255,-1265), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Level time: 13839874 game time, 1565989 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1004914920 bytes (958 MB) / 2562433024 bytes (2443 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version       | Source                             | Signature                                |
	|:--------- |:-------------------- |:------------- |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2        | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp                  | 9.42          | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | actuallyadditions    | 1.12.2-r141   | ActuallyAdditions-1.12.2-r141.jar  | None                                     |
	| UCHIJAAAA | quark                | r1.5-129      | Quark-r1.5-129.jar                 | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-20        | AutoRegLib-1.3-20.jar              | None                                     |
	| UCHIJAAAA | endercore            | 1.12.2-0.5.41 | EnderCore-1.12.2-0.5.41.jar        | None                                     |
	| UCHIJAAAA | jei                  | 4.12.1.217    | jei_1.12.2-4.12.1.217.jar          | None                                     |
	| UCHIJAAAA | enderio              | 5.0.36        | EnderIO-base-1.12.2-5.0.36.jar     | None                                     |
	| UCHIJAAAA | enderiobase          | 5.0.36        | EnderIO-base-1.12.2-5.0.36.jar     | None                                     |
	| UCHIJAAAA | enderiomachines      | 5.0.36        | EnderIO-machines-1.12.2-5.0.36.jar | None                                     |
	| UCHIJAAAA | extrautils2          | 1.0           | extrautils2-1.12-1.9.6.jar         | None                                     |
	| UCHIJAAAA | waila                | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar        | None                                     |
	| UCHIJAAAA | refinedstorage       | 1.6.8         | refinedstorage-1.6.8.jar           | None                                     |
	| UCHIJAAAA | refinedstorageaddons | 0.4.2         | refinedstorageaddons-0.4.2.jar     | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
LoadingPlugin (Quark-r1.5-129.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	All players: 1 total;
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Shadows-of-Fire** [comment] 2018-10-22 16:32
Duplicate of #1191

**Closed by Shadows-of-Fire** 2018-10-22 16:32 UTC
