### ISSUE TITLE
client crash 

### ISSUE THREAD

**Issue by OldManCraft** [Ellpeck/ActuallyAdditions#1070] opened 2018-04-12 19:55 UTC
Forge 1.12.2 2657

java.lang.NullPointerException: Initializing game
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.getCapability(ItemEnergy.java:230)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.hasCapability(ItemEnergy.java:222)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:94)
	at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1162)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_150895_a(ItemEnergy.java:77)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.getCapability(ItemEnergy.java:230)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy$EnergyCapabilityProvider.hasCapability(ItemEnergy.java:222)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:94)
	at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1162)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_150895_a(ItemEnergy.java:77)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by PolarizedIons** [comment] 2018-04-12 19:56
duplicate of #1068 and #1069  - don't use forge 2657

**Comment by OldManCraft** [comment] 2018-04-12 19:58
What is the highest forge it works with

**Comment by PolarizedIons** [comment] 2018-04-12 20:03
I'm not sure, just through I'd try be helpful with marking it as duplicate. I'd try a version below though

**Closed** 2018-04-12 20:02 UTC
