### ISSUE TITLE
Tinkes Crafting Table next to Item Interface misbehaves

### ISSUE THREAD

**Issue by ASDFGamer** [Ellpeck/ActuallyAdditions#491] opened 2016-12-15 20:09 UTC
I had a Problem with my tinker crafting station next to an Item Interface that connects to my crate storage. I was not able to reproduce it but sometimes when I have some Items of the recipie in my Inventory and some in the crates some Items out of my Inventory disapear and are not in the storage system. 
I had that Problem expecially with the machine casing from EnderIO with the capacitor in a crate and the iron bars and ingots in my Inventory each time I shift-clicked from JEI 4 iron bars and ingots disapeard but the capacitor didn't move and the items didn't reapear. But when I took the capacitors out and in again the problem disapeard. 
Another Problem I found that is maybe related to that is that if all Items are in the crates JEI shows that all Items are present but they dont go into the crafting table

Playing Direwolf20 1.10 pack version 1.1.4 (forge 2171, Actually Additions r88, TConstruct 2.5.6b, JEI 3.13.6.387)

**Comment by Ellpeck** [comment] 2016-12-15 20:34
Duplicate of #410, there's nothing I can do here as it appears that this isn't a problem on Actually Additions' side.

**Closed by Ellpeck** 2016-12-15 20:34 UTC
