### ISSUE TITLE
Storage Crate upgrades not working.

### ISSUE THREAD

**Issue by PetersonE1** [Ellpeck/ActuallyAdditions#413] opened 2016-11-26 21:02 UTC
The storage crate upgrades won't do anything when shift-clicked onto the crates.  However, this problem does not occur in singleplayer.

**Comment by Ellpeck** [comment] 2016-11-26 21:52
I can't reproduce this.

**Comment by Ellpeck** [comment] 2016-11-30 17:30
Please make this clear, otherwise the issue will be closed as I can't reproduce this.

**Closed** 2016-12-01 21:08 UTC
Labels: bug, investigate, waiting
