### ISSUE TITLE
so close ellpack so close hehehehe  hopper issue

### ISSUE THREAD

**Issue by 5kedone** [Ellpeck/ActuallyAdditions#453] opened 2016-12-05 14:54 UTC
now hoppers insert correct amount of biomass in compost bin but wont pull compost out of it, oh and increasing bin size much better 

ActuallyAdditions-1.11-r89
latest forge

**Comment by Ellpeck** [comment] 2016-12-05 15:04
Can't reproduce.

**Comment by 5kedone** [comment] 2016-12-05 15:43
What me to obs it ?

**Comment by Ellpeck** [comment] 2016-12-05 15:45
...what?

**Comment by tigier** [comment] 2016-12-05 15:50
Ich glaube er bietet dir an es mit OBS aufzunehmen

**Comment by 5kedone** [comment] 2016-12-05 15:53
dont worry i did it, here is youtube video of it happening https://www.youtube.com/watch?v=6SY50PzOURM&feature=youtu.be

**Comment by Ellpeck** [comment] 2016-12-05 16:11
I updated Forge and I still can't reproduce it. Did you try this in a different location / after replacing the block?

**Comment by 5kedone** [comment] 2016-12-05 16:24
Starting a new world as we speak will let you know

**Comment by 5kedone** [comment] 2016-12-05 16:42
nope still the same see, now this is weird
![2016-12-05_16 29 15](https://cloud.githubusercontent.com/assets/2697002/20893474/d31c1a58-bb09-11e6-98df-e79ca4e753f0.png)

**Comment by Ellpeck** [comment] 2016-12-05 16:43
This doesn't make any sense. Can you try with just Actually Additions installed? :v

**Comment by 5kedone** [comment] 2016-12-05 16:44
As its you hang on

**Comment by 5kedone** [comment] 2016-12-05 17:02
Clean only your mod it works woohooo right I will try and track what mod is
doing it

**Comment by Ellpeck** [comment] 2016-12-05 17:03
Thanks :)

**Comment by 5kedone** [comment] 2016-12-05 17:05
Give me a day or two gonna have to test one by one YUCK

**Comment by Ellpeck** [comment] 2016-12-05 17:07
You don't. Just uninstall half of the mods. If the bug is still there, uninstall another half, etc. It doesn't take long if you do it that way.

**Comment by 5kedone** [comment] 2016-12-05 17:09
Yeah I know just home life also slows me down lol

**Comment by 5kedone** [comment] 2016-12-05 17:12
Also there is the loading time and waiting for it to make bloody compost

**Comment by 5kedone** [comment] 2016-12-05 17:54
got it , found the culprit its betterfps mod if fast hopper mode is on it stops out put , but only with your mod, no other mod seems to be effected ?

**Comment by Ellpeck** [comment] 2016-12-05 17:57
I removed IInventory support, maybe the fast version doesn't support Capabilities.
I will close this for now then.

**Closed by Ellpeck** 2016-12-05 17:57 UTC
Labels: bug, investigate, waiting

**Comment by 5kedone** [comment] 2016-12-05 17:59
Could well be but atleast I know what it is and that dont make much of a
diff for tps in my worlds lol
