### ISSUE TITLE
QUESTION: problems with ESD

### ISSUE THREAD

**Issue by garath77** [Ellpeck/ActuallyAdditions#353] opened 2016-11-12 14:26 UTC
I'm having problems getting the ESD and Advanced ESD blocks to work. I've read the manual and followed what little there is there. I'm assuming that it is supposed to be pretty self-explanatory, but I can't get it to pull from a chest or any other inventory. I set the input and output ranges, but I can't get the inbound and outbound areas to say anything other than disabled. What am I doing wrong?

Thanks for your help and all your hard work on this mod. I love it!

**Comment by Ellpeck** [comment] 2016-11-12 14:31
What are the inventories you are using? Are they definitely the right directions?

**Comment by garath77** [comment] 2016-11-12 15:15
As I face the ESD, I have a plain chest to the left as the input and a plain chest to the right as the output.
I'll post screenshots as soon as I can.

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 12, 2016 at 8:31 AM, Ellpeck<notifications@github.com> wrote:   
What are the inventories you are using? Are they definitely the right directions?

**Comment by Ellpeck** [comment] 2016-11-12 15:31
You're trying to send the items between slot 1 (inclusive) and slot 1 (exclusive), meaning *no slot at all*.
As you can see when you hover over the text boxes in the ESD GUI, the first number is always inclusive while the second one is exclusive.
Say, you want to pull from slots 1, 2 and 3, then you'd have to set the range in the ESD from 1 to 4. :)

**Comment by garath77** [comment] 2016-11-12 15:37
OK, so I just changed them so they are both reading 1 - 27, so the pull and put should both be from slots 1-26. Still nothing is moving. Is there something I need to do to make it start?

**Comment by Ellpeck** [comment] 2016-11-12 15:49
So from left to right, the boxes now say 1, 27, 1, 27?
It isn't allowed to be powered by redstone. Try putting the items into the other chest - maybe you got the sides wrong?

**Comment by garath77** [comment] 2016-11-12 15:53
That is how they read. There is no redstone anywhere withing at least 10 blocks of this setup. I just tried moving the items to the other chest and still got no movement. Both the areas between the < > in the GUI say DISABLED. Are those supposed to change?

**Comment by Ellpeck** [comment] 2016-11-12 15:55
Well, yes, obviously. You need to define the sides you want to put and pull items. :x

**Comment by garath77** [comment] 2016-11-12 15:58
I tried to do that by pressing the corresponding directional button, which did nothing for me, then I tried pressing the checkmark button, also nothing.

Sorry for being such a pain. It was pretty late last night when I started working with these, so I wasn't the most clear-headed. Unfortunately, I'm obviously not much better today. LOL

**Comment by Ellpeck** [comment] 2016-11-12 15:59
You need to click the button until the right direction appears. You can check in your F3 menu which direction you need.

**Comment by Ellpeck** [comment] 2016-11-12 16:00
Once it appears, the slots will also automatically change to the right numbers. - It's not that hard.

**Comment by garath77** [comment] 2016-11-12 16:03
My input chest is to the north of the ESD, the output to the south. No matter how many times I press the left or right arrows for the inbound, it never changes from DISABLED.

**Comment by Ellpeck** [comment] 2016-11-12 16:05
What?
Well, this *is* a bug. Which MC, Forge and mod version are you on?

**Comment by garath77** [comment] 2016-11-12 16:09
MC 1.10.2
Forge 2124
AA r70

**Comment by Ellpeck** [comment] 2016-11-12 16:10
Well, I only know I can't reproduce this. Would you mind making a video of it?

**Comment by garath77** [comment] 2016-11-12 16:17
I'll play around with it some more. I'll try to vid if I can't get it to work now that I know how it is supposed to work. Thanks for your help.

**Comment by garath77** [comment] 2016-11-12 16:38
So there definitely seems to be a bug, but not directly with the ESD. I got it to work by logging out of my world and logging back in. Now it works fine. I ran into this same issue when creating the Traveler's Pack. I couldn't change any of the whitelist/blacklist or NBT/Metadata setting on it without re-logging. I was able to reproduce this 2 more times with the Pack. So far, these are the only 2 items I've had this issue with, but I suspect there could be more, possibly anything with configurable settings like this.

**Comment by Ellpeck** [comment] 2016-11-12 16:40
It's probably not syncing correctly - I'm guessing? Does either the client or the server log say anything suspicious?

**Comment by garath77** [comment] 2016-11-12 17:03
I'm not seeing anything. Only the loading entries...

**Comment by Ellpeck** [comment] 2016-11-12 17:07
That's very weird. Please make a video.

**Comment by garath77** [comment] 2016-11-12 17:09
I'll try to reproduce in a new world. Maybe it's a conflict with one of my other mods...

**Comment by garath77** [comment] 2016-11-13 22:43
After testing in a new world with only AA (and failing to reproduce the issue), I can only assume a conflict of some kind with one of my other mods. I'll play around some more and see if I can narrow down which one it might be. Thanks for all you help.

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 12, 2016 at 11:07 AM, Ellpeck<notifications@github.com> wrote:   
That's very weird. Please make a video.

**Comment by Ellpeck** [comment] 2016-11-17 15:32
What about this? :o
Can I close this or is the issue still appearing?

**Comment by garath77** [comment] 2016-11-17 19:22
I'll close it for now, I still haven't figured anything more yet. I reserve the right to reopen if I do find something more. :P

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 17, 2016 at 9:32 AM, Ellpeck<notifications@github.com> wrote:   
What about this? :o
Can I close this or is the issue still appearing?

**Closed** 2016-11-17 19:22 UTC
Labels: bug, investigate, waiting
