### ISSUE TITLE
Crash in 1.12 with your mod

### ISSUE THREAD

**Issue by Migmag789** [Ellpeck/ActuallyAdditions#822] opened 2017-06-29 10:10 UTC
Actually Additions crashed :/
[crash-2017-06-29_12.08.12-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1111619/crash-2017-06-29_12.08.12-client.txt)

**Comment by Ellpeck** [comment] 2017-06-29 10:20
It doesn't look like this issue is caused by Actually Additions.
Paging @TehNut though.

**Comment by Migmag789** [comment] 2017-06-29 11:05
New crash, after deleting many mods listed on "errored" : 
https://pastebin.com/ke2bK0Jv

**Comment by Ellpeck** [comment] 2017-06-29 11:05
Yea there we go, now it's a duplicate of #820 which is a duplicate of #811.
Nice.

**Closed by Ellpeck** 2017-06-29 11:05 UTC
Labels: investigate

**Comment by TehNut** [comment] 2017-06-29 12:41
Yeah that first one has already been reported to me, I just haven't gotten a chance to fix it.
