### ISSUE TITLE
Infinite Redstone?

### ISSUE THREAD

**Issue by M4thG33k** [Ellpeck/ActuallyAdditions#818] opened 2017-06-27 17:03 UTC
Placing either redstone or redstone blocks into the Precision Dropper has it drop the respective item/block infinitely without emptying the Dropper's internal inventory. 

Currently using version 1.11.2-r109, but didn't notice any reference to this issue in newer change logs. Thanks!

The Twitch import folder for the pack where this issue is found:
[Buggy Pack-1.0.zip](https://github.com/Ellpeck/ActuallyAdditions/files/1106173/Buggy.Pack-1.0.zip)

**Comment by Ellpeck** [comment] 2017-06-27 17:23
Duplicate of #799 which is a duplicate of #747.
If I get this report one more time, @SonarSonic, I am going to literally nuke the moon. :V

**Closed by Ellpeck** 2017-06-27 17:23 UTC
