### ISSUE TITLE
Automatic Precision Dropper cloning redstone

### ISSUE THREAD

**Issue by SeriousDan** [Ellpeck/ActuallyAdditions#855] opened 2017-07-18 22:31 UTC
I tried to automate an automatic precision dropper for crystals but as soon as I placed a redstone dust in in it started dropping about 3 stacks of redstone without consuming the one I had put first. This only happens with redstone and I can only stop it with a redstone signal. I suspected the Refined Storage crafter was putting more than 1 redstone but it still happened after I disconnected it.

**Comment by JonathanxD** [comment] 2017-07-18 22:47
Do you have `FluxNetworks` installed? If yes, this is duplicated of #747 (which seems to have some duplications)

**Comment by Shadows-of-Fire** [comment] 2017-07-18 22:57
Cannot reproduce (1.12-r115).  This is not on our end.  Duplicate of #747

**Closed** 2017-07-18 23:39 UTC

**Comment by SeriousDan** [comment] 2017-07-18 23:45
Yes I have flux networks.
Had to use a vanilla dropper instead but thanks for the explanation.
