### ISSUE TITLE
Precision Dropper + Redstone = dupe bug

### ISSUE THREAD

**Issue by kragnoth** [Ellpeck/ActuallyAdditions#799] opened 2017-06-04 00:06 UTC
1.11.2 r109 of actually additions.

I've built a Refined storage combination of a crafter and a precision dropper to craft flux.  I placed a redstone into the precision dropper to test its ... precision, and it is dropping infinite redstone.  It is oriented with a forestry wrench to face downwards.

Forge version is 2302

**Comment by Ellpeck** [comment] 2017-06-04 08:49
Duplicate of #747, not an issue on my side.

**Closed by Ellpeck** 2017-06-04 08:49 UTC

**Comment by kragnoth** [comment] 2017-06-04 14:09
heh, I guess I should have tried uninstalling flux networks first.  Thanks for the fast response.
