### ISSUE TITLE
[1.10.2] onCraftedEvent() Exception spamming server console

### ISSUE THREAD

**Issue by PotatoSauceVFX** [Ellpeck/ActuallyAdditions#609] opened 2017-01-31 04:12 UTC
I went to check my server console the other day and it was just spamming a bunch of NullPointerExceptions for onCraftedEvent(). Everything seems to be working fine on the server but this is just annoying since I can't read console.
[fml-latest log.txt](https://github.com/Ellpeck/ActuallyAdditions/files/741084/fml-latest.log.txt)

I am using sponge 1.10.2 so I'm not sure if this is a sponge problem or a Actually Additions problem.

**Comment by PotatoSauceVFX** [comment] 2017-01-31 13:29
I pulled out Sponge and is spams a similar exception.
[fml-latest.txt](https://github.com/Ellpeck/ActuallyAdditions/files/742042/fml-latest.txt)

**Comment by Ellpeck** [comment] 2017-01-31 13:32
Try removing other mods and see if the problem persists. If not, try to find out which mod is causing it.

**Comment by PotatoSauceVFX** [comment] 2017-02-01 12:30
Not sure what I did. I just restarted it to make a copy to test with and I started it back up. It seems to have stopped now. Thanks for your time. I'll put an update if something happens again.

**Comment by PotatoSauceVFX** [comment] 2017-02-01 12:54
Spoke too soon, it's back. Seems like it's happening with a chunk or something.

**Comment by Ellpeck** [comment] 2017-02-01 13:26
Is that without any other mods installed?

**Comment by PotatoSauceVFX** [comment] 2017-02-01 13:49
No, but I have no idea what player is causing it and what chunk loads that causes the exception to start spamming.

**Comment by Ellpeck** [comment] 2017-02-13 14:30
Is there any more info on this? Otherwise, I will close this issue as I cannot reproduce it.

**Closed** 2017-02-14 21:50 UTC
Labels: bug, investigate, waiting
