### ISSUE TITLE
Crash with Greenhouse Glass

### ISSUE THREAD

**Issue by djkid** [Ellpeck/ActuallyAdditions#1193] opened 2018-10-15 01:08 UTC
Looks like a problem when updating plant state.

[crash-2018-10-14_20.02.17-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2477077/crash-2018-10-14_20.02.17-server.txt)

**Comment by Shadows-of-Fire** [comment] 2018-10-16 23:37
Duplicate of #1191

**Closed by Shadows-of-Fire** 2018-10-16 23:37 UTC
