### ISSUE TITLE
1.12-r111 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [Ellpeck/ActuallyAdditions#820] opened 2017-06-28 16:20 UTC
Notes:
     on startup

crash report:
https://gist.github.com/1368bc6b372fe03add53b0635be9887a

fml server latest:
https://gist.github.com/cbe7cad04dcf2302d961b757ff067eda

possibly related: #811

**Comment by Ellpeck** [comment] 2017-06-28 16:21
Duplicate of #811.
Look at existing issues first before reporting.

**Closed by Ellpeck** 2017-06-28 16:21 UTC
