### ISSUE TITLE
Atomic reconstructor with lens of color causes server crash when used on beetroots

### ISSUE THREAD

**Issue by ab9rf** [Ellpeck/ActuallyAdditions#921] opened 2017-09-16 03:38 UTC
Place stack of 64 beetroots (not rose red dye, beetroots) in front of atomic reconstructor. 
Install lens of color on atomic reconstructor.
Fire atomic reconstructor.

Result:
```Description: Exception while ticking a block

java.lang.IllegalStateException: Actually Additions: Something is incredibly wrong.  I don't know what you did, or how this method got called.  But something is just completely wrong.  This method was provided with 
0:class java.lang.String<- CLASS | INSTANCE ->Oh yeah some idiot somewhere threw a null itemstack at us, might've been us, but whatever, 
```

Full crash report [here](https://gist.github.com/ab9rf/a2fd5f3a22b710d11fe7265e46c55add).

MC 1.12.1
Forge 14.22.0.2474
ActuallyAdditions 1.12.1-r119

**Comment by Shadows-of-Fire** [comment] 2017-09-16 03:48
Duplicate of #912

**Closed by Shadows-of-Fire** 2017-09-16 03:48 UTC
