### ISSUE TITLE
[1.10.2] Major server startup crash dropping solidified experience in the world

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#404] opened 2016-11-24 14:43 UTC
This did not happen with r71, I updated to r75 and crash occured, tried r79 crash still present.

http://pastebin.ubuntu.com/23527251/

To replicate:-
Take an extra utils "Mechanical User" and set it to use the solidified experience, this drops actual experience on the floor which was then picked up by an EnderIO XP vacuum and stored in a EnderIO XP Obelisk.

Upon updating the server crashes with the above crash, it will not start as the crash is fatal.

Reverting to r71 made it so the server started up and we could break the Mechanical User.  I guess the solidified experience doesn't like being used by a non-player now?

**Comment by Ellpeck** [comment] 2016-11-24 15:40
That's.. weird.

**Comment by canitzp** [comment] 2016-11-24 15:43
maybe the fake player of the mechanical user does not work correct. the npe is caused by the playerinteractionmanager

**Comment by Ellpeck** [comment] 2016-11-24 15:46
Does it also happen when you use the item as a player?

**Comment by b0bst3r** [comment] 2016-11-24 15:58
No and I think because maybe nothing is dropped into the world (that I can see), the xp goes straight into your bar.

**Comment by Ellpeck** [comment] 2016-11-24 16:00
XP Orbs are being dropped, you just pick them up directly.
Please report this to Extra Utilities, this seems like a bug from the mod.
Also please mention this issue in that issue so that I can keep updated :)

**Comment by Ellpeck** [comment] 2016-11-24 16:33
Are you sure this is connected to updating Actually Additions and not some other mod like ExU itself?
I didn't change anything from r74 to r75 related to Solid XP.

**Comment by b0bst3r** [comment] 2016-11-24 16:42
Yes, I initially thought it might have been the extrautils update so I back dated that and it still crashed, so I've tried r79 with both versions of ExUtils.  

At the same time as I updated extra utils I also updated to r75 and that introduced the crash.  As I already stated r71 works, r75-79 crash with both extra utils 1.10.2-1.1.0 and the previous version extrautils2-1.10.2-alpha-1.2.2

**Comment by Ellpeck** [comment] 2016-11-28 17:21
I'll close this for now, but please try to keep this issue updated about if there's any fix from the side of Extra Utilities.

**Closed by Ellpeck** 2016-11-28 17:21 UTC
Labels: bug, gamebreaking, investigate, waiting
